### ISSUE TITLE
after installing mail debrand in odoo 15 community edition digest email not display properly showing HTML code instead of message

### ISSUE THREAD

**Issue by Zebrando** [OCA/social#1004]
Hi,

I have an issue after installing mail debrand in odoo 15 community edition digest email does not display properly, showing HTML code instead of the message, is there any solution for this? below is the attached screenshot.
![image](https://user-images.githubusercontent.com/106875727/204213637-a0a16304-8014-4667-a389-50b82b661ad6.png)

**Comment by arturoovf** [comment]
I'm seeing same thing, not reliable to have the module installed

**Comment by arturoovf** [comment]
I ended up uninstalling and modifying the templates myself

**Comment by dhx** [comment]
Had the same issue, should be solved in the meantime with #939

**Comment by rrebollo** [comment]
@dhx @rven @pedrobaeza @joao-p-marques this is back again at 15.0 branch. Tested in runboat.
My workaround involved to change:
https://github.com/OCA/social/blob/938f9ec7bda6d7960e5e3bc38fc39508bd9d3cad/mail_debrand/models/mail_render_mixin.py#L54-L56
To:
`value = Markup(html.tostring(
                tree, pretty_print=True, method="html", encoding="unicode"
            ))`

**Comment by Garibaldy** [comment]
> @dhx @rven @pedrobaeza @joao-p-marques this is back again at 15.0 branch. Tested in runboat. My workaround involved to change:
> 
> https://github.com/OCA/social/blob/938f9ec7bda6d7960e5e3bc38fc39508bd9d3cad/mail_debrand/models/mail_render_mixin.py#L54-L56
> 
> 
> To:
> `value = Markup(html.tostring( tree, pretty_print=True, method="html", encoding="unicode" ))`

@rrebollo this should be in a pull request to be merged,  as today  this is not been solved in the latest version of mail_debrand  module"version": "15.0.1.2.4" , does there is a reason why i hasn't been done yet ?

**Comment by rrebollo** [comment]
@Garibaldy suggested workaround doesn't fix the issue either for some mail templates.Ex: mail template to invite new users is broken by the attend to replace odoo links using regex. I ended up modifying the mail templates.

**Comment by dhx** [comment]
@Garibaldy Possible alternative to replace the templates: https://github.com/OCA/social/tree/15.0/mail_layout_force
( PR for 16.0: https://github.com/OCA/social/pull/1069 )

**Comment by Garibaldy** [comment]
> @Garibaldy suggested workaround doesn't fix the issue either for some mail templates.Ex: mail template to invite new users is broken by the attend to replace odoo links using regex. I ended up modifying the mail templates.

i double checked twice all templates and it seems to be working just right with your workaround,

maybe because a pull request  that was made after your suggestion like this one metioned before https://github.com/OCA/social/pull/939 , fixed most of the things except digest
