### ISSUE TITLE
[15.0] microsoft_outlook_single_tenant: Error on tests

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/social#1061]
This module is provoking an error in the CI:

https://github.com/OCA/social/actions/runs/4062982084/jobs/6994667509#step:8:679

It may be due to the changes Odoo has changed upstream: 8f623307749a395b1399d3e8b128e375a94d97ae. I think this makes the module useless (or it can be kept for easy config).

But in any case, the tests should be fixed.

@santostelmo can you please check?

**Comment by santostelmo** [comment]
Thanks @pedrobaeza good news that odoo added that in standard. Indeed that module became useless after commit 8f623307749a395b1399d3e8b128e375a94d97ae

**Comment by pedrobaeza** [comment]
Can you then fix the tests on existing module or remove them?

**Comment by santostelmo** [comment]
Yes I will

**Comment by santostelmo** [comment]
@pedrobaeza PRs for that issue referenced above.

**Comment by pedrobaeza** [comment]
Thanks!
