### ISSUE TITLE
[15.0] mail_debrand: Problem with newsletter emails

### ISSUE THREAD

**Issue by OKT96** [OCA/social#1066]
## Module
mail_debrand

## Describe the bug
When the mail_debrand module is installed, the newsletter emails sent with mass_mailing module are being sent as plain text instead of html:
![image](https://user-images.githubusercontent.com/85667041/217290464-ef5de7af-066b-4fa9-9e42-f667f17d2a64.png)

## To Reproduce

1. Install the mail_debrand module
2. Send a newsletter email through the mass_mailing module

**Expected behavior**
The newsletter email should be sent as html, with proper formatting and styling

**Additional context**
The problem lies in the `_replace_local_links` function in the `mail_render_mixing.py` file. This function should return a `Markup()` object, but it is returning `str` in this use case, which causes the emails to be sent as plain text

**Comment by pedrobaeza** [comment]
We have just merged #939, which fixes this in theory. Write again if not.
