### ISSUE TITLE
[15.0] mail_tracking: portal tests fail

### ISSUE THREAD

**Issue by jonasbuchholz** [OCA/social#1067]
## Module
mail_tracking

## Describe the bug
mail_tracking causes TestPortalWizard.test_portal_wizard_public_user and TestPortalWizard.test_portal_wizard_partner to fail

## To Reproduce
**Affected versions**: 15.0

1. init db with portal and mail_tracking
2. run portal tests

**Comment by pedrobaeza** [comment]
Please don't open an issue if you are going to open a PR. Put the issue description in the PR. Anyway, the issue description you have put is not enough. Put more information on the PR.
