### ISSUE TITLE
mail_restrict_follower_selection: database upgrade will recreate the default restriction

### ISSUE THREAD

**Issue by gurneyalex** [OCA/social#1070]
The mail_restrict_follower_selection module comes with a default setup which is overly restrictive: only partners with tag "Employees" are eligible. I think this is inapropriate as a default rule (for instance it makes runboat instances for OCA/social difficult to use, since by default in Odoo there are no such partners in the demo data. 

Since customers typically want something more subtle, they will create a per model configuration in the system parameters of the instance and delete the global rule. This has an unintended consequence if someone runs "update base" as the super restrictive rule is recreated during the update of the module.

Ideally this example configuration would be in the demo data, not in the module data, but changing this would probably create a migration issue that I'm not entirely sure how to handle. Therefore, I propose:

* use forecreate=false in mail_restrict_follower_selection/data/ir_config_parameter.xml so that a deleted configuration is not recreated by a module update
* I would also like to change the default domain to something less agressive: for instance [(1, '=', 1)] and if required fix the tests if they depend on the module data
* in the demo data, add an example restriction restricting following a specific model

This domain is present since 13.0 (in previous odoo versions we had something less dramatic but still annoying as a default global filter IMO)

**Comment by yostashiro** [comment]
Sounds reasonable to me. 👍
