### ISSUE TITLE
[16.0] OCA/social/mail_debrand _> New Portal Signup email body empty / Odoo Periodic Digest html

### ISSUE THREAD

**Issue by ser-tec** [OCA/social#1090]
## Module
OCA/social/mail_debrand

## Describe the bug
After mail_debrand installation, New Portal Signup email body become empty and Odoo Periodic Digest is not rendered (mail is plain text)

## To Reproduce
**Affected versions**: 16

1. install mail_debrand
2. try to invite a new user and check email or setting->review all template->Settings: New Portal Signup->preview
3. try to send odoo Periodic Digest or preview the template

**Additional context**
ubuntu 20.4
odoo16
mail_debrand 16.0.1.0.0

## Attached examples

_Example New Portal Signup email body empty_

![Immagine](https://user-images.githubusercontent.com/113360845/223399779-38b87f02-ab3f-4aac-b804-63d0301427c3.jpg)

_Example Odoo Periodic Digest html_

![Immagine2](https://user-images.githubusercontent.com/113360845/223399785-ea7226d4-a96a-4a35-a324-43ced6ceb3dc.jpg)

**Comment by jeffreyouni** [comment]
I have the same problem, please help!

**Comment by Florian-Laport** [comment]
This is the same issue as #936. In the mail_debrand module, `_render_template` calls the `remove_href_odoo` function without wrapping its return value in a MarkupSafe object. This function returns a plain string regardless of input become its output comes from `etree.tostring()`.

**Comment by Priddybroderickson** [comment]
Thank you for detailing the issue you're facing with the OCA/social/mail_debrand installation. It seems to be affecting the email body content and rendering in Odoo, particularly the New Portal Signup email and the Odoo Periodic Digest. This bug appears to be present in version 16. Your provided steps to reproduce the issue and additional context will be valuable in [Sterne](https://zarasocial.com/category/deutsche-sterne/) addressing this concern effectively. It's recommended to consider reaching out to the Odoo community or support for further assistance.

**Comment by mathben** [comment]
Check my fix for Odoo 14 #1215

**Comment by raulovallet** [comment]
I have same issue

**Comment by raulovallet** [comment]
> Check my fix for Odoo 14 #1215


I tried this and it have same problem in v15.0 
![Screenshot 2023-11-15 at 2 49 02 PM](https://github.com/OCA/social/assets/23384474/08069cfc-fdc5-4152-b251-3584a8d66d04)
<img width="1175" alt="Screenshot 2023-11-15 at 2 49 26 PM" src="https://github.com/OCA/social/assets/23384474/0d4011ad-0658-4219-b583-f046f558af29">
