### ISSUE TITLE
[14.0][mail_tracking] Question about bounce email

### ISSUE THREAD

**Issue by TDu** [OCA/social#1121]
Hello @OCA/social-maintainers ,

This is a question about how the `mail_tracking` module handles and logs bounce emails ?

From the couple of instances with the `mail_tracking` module installed (v14, but probably the same for newer version) I do not see any occurrence of bounce state being logged in the `mail.tracking.event`  or `mail.tracking.email` table ?

From looking at the code the only way it could happen is through a controller and custom function. But this solution has been marked as to remove  https://github.com/OCA/social/commit/54337a95c1297acadb5200f79712896575be840b

Does anyone has this working ? Or knows how it should work in theory ?

Thank you in advance.

**Comment by chienandalu** [comment]
This can be closed as it was already addressed
