### ISSUE TITLE
[15.0] mail_outbound_static > Odoo ir_mail_server.py overwrites smtp_from so that module is useless

### ISSUE THREAD

**Issue by david-fleischmann** [OCA/social#1131]
## Module
mail_outbound_static 

## Describe the bug
When sending an email without a template as for example from res.partner the smtp_from field provided by this module is NOT taken into account. It will send it from user's email

## To Reproduce
**Affected versions**: 15.0 

1. install mail_outbound_static
2. go to res.partner record and click on send message and send some sample text
3. email recipients email from mail header will contain the user's mail address

**Expected behavior**
Normally the recipient should receive the email from the address set in smtp_from

**Additional context**
After debugging the cause we fixed that issue by patching odoo itself inside ir_mail_server.py
But this cannot be the intended behaviour of this module?

![image](https://user-images.githubusercontent.com/73656049/232551071-f0edd51c-7af3-4fca-8915-92f7c7c5b9c6.png)

**Comment by david-fleischmann** [comment]
btw: I didn't set a domain whitelist value in order to overwrite EVERY Email From so we can use one single mail address and server without spf configuration

**Comment by yostashiro** [comment]
@david-fleischmann Are you using the latest code? I thought https://github.com/OCA/social/pull/1051 would fix your issue.
