### ISSUE TITLE
Issue when reset email is sent from odoo

### ISSUE THREAD

**Issue by msak670** [OCA/social#1195]
There's an issue with this module that needs attention. When it processes emails, it mistakenly removes important links. A clear example of this is seen in the password reset feature: instead of sending an email with a clickable button or link to reset the password, the email arrives without that crucial link. This not only hampers the user experience but also defeats the purpose of the feature. If this issue persists, many users might find this module ineffective and not fit for its intended purpose.

**Comment by filcius** [comment]
which module exactly?

**Comment by msak670** [comment]
mail debrand module

**Comment by mathben** [comment]
Do you have this bug with Odoo 14?
I did a fix for this issue, I had the same problem with password reset feature.
#1215
