### ISSUE TITLE
mail_debrand immediately breaks any online form ticket submissions in Odoo 16

### ISSUE THREAD

**Issue by smileBeda** [OCA/social#1200]
## Module
`mail_debrand`

## Describe the bug
Installed the module and submitted a ticket in the Odoo online Ticket submission form to test if it would indeed debrand the mail.
It immediately breaks with Error 500 on the request `helpdesk.ticket`
Problem immediately goes away if uninstalling the module.

**Comment by StefanRijnhart** [comment]
Do you have a traceback from the server log file perhaps?

**Comment by smileBeda** [comment]
Hi, unfortunately I don’t use Odoo anymore. Or, maybe fortunately. It’s not exactly the most stable software I’ve used in my life, and there've been other opportunities to test meanwhile so I moved on.

Thus I can’t replicate this atm. 

Thanks.

**Comment by StefanRijnhart** [comment]
@smileBeda thanks for the follow-up!
