### ISSUE TITLE
V14 - Mass Mailing Subscription Management by Portal User

### ISSUE THREAD

**Issue by TumbaoJu** [OCA/social#1255]
I would like to know if there is an existing module that let the portal user manage his own Mailing List Subscriptions from his Portal account or if not, is there anyone already working on this kind of feature ?

I know that in Standard Odoo, this management can be done from the _"Unsubscribe"_ button available in the bottom of a maliling.
![Unsubscribe_mailing](https://github.com/OCA/social/assets/38360781/48c677e9-ddc0-428c-ac7a-6cc971d9b73b)

Once the user click on this button, he can unsubscribe from the mailing list linked to the email and after that, access the list of his subscriptions.
![Mailing_list_management_page](https://github.com/OCA/social/assets/38360781/fa98a760-2a99-4017-9528-330129bb8c17)

So the need would be to be able, as a portal user, to access this list from my portal page.

Thank you in advance!

**Comment by TumbaoJu** [comment]
@francesco-ooops : Have you even had the same need?

**Comment by pedrobaeza** [comment]
I don't know any, but I don't think it's too complicated to be done based on the existing feature. And additional feature may be to link the mailing list to a website, and only show the lists corresponding to the current website.

**Comment by francesco-ooops** [comment]
Hi @TumbaoJu , unfortunately I've never worked with this app/area so I can't provide an insight on this

**Comment by TumbaoJu** [comment]
Thank you @pedrobaeza and @francesco-ooops for taking the time to answer.

@pedrobaeza : We were planning on developping the feature (it will depend on the customer) but before, I wanted to be sure not to develop something in double.

**Comment by pedrobaeza** [comment]
Great, a welcome OCA addition :smiley:

**Comment by TumbaoJu** [comment]
It could be if the customer decides to go in that direction.  We will see.
