### ISSUE TITLE
[16.0] mail_composer_cc_bcc: setting Cc or Bcc causes an unwanted mail to be sent

### ISSUE THREAD

**Issue by msaeedhp** [OCA/social#1263]
## Module
mail_composer_cc_bcc

## Describe the bug
When using the mail_composer_cc_bcc module, in the Purchase module and after sending a Request for Quotation via email to the vendor, if you provide any Cc or Bcc email address, an additional email is sent notifying Cc and Bcc recipients about the status change (RFQ to RFQ Sent).

## To Reproduce
**Affected versions**: 16.0.1.0.0

1. Install the mail_composer_cc_bcc module.
2. In the Purchase module, create a new Request for Quotation.
3. Choose a vendor, save, and click on SEND BY EMAIL.
4. Enter an email in the Cc or Bcc field or both.
 
![image](https://github.com/OCA/social/assets/36600765/dbc7e600-1f64-405c-a166-4c6e4f3f8a7e)

5. Click on SEND

**Expected behavior**
An email should have been sent to the recipient(s) and email addresses provided in Cc and Bcc mail about the details of the RFQ (request for quotation) without any additional emails being sent.
But as you can see in the image below, an additional email was sent to Cc and Bcc emails notifying them about the change in RFQ status, which is not the expected behavior.

![image](https://github.com/OCA/social/assets/36600765/a192ff53-a271-46b0-99de-73a98c56e31c)

![image](https://github.com/OCA/social/assets/36600765/ed529cb7-936a-48e6-868d-883499d93bc6)

**Additional context**
Odoo version 16
Python version 3.10

**Comment by TTPBruce** [comment]
Also an issue in 15.0

I think "partner_bcc_ids" and "partner_cc_ids" context values need to be cleared at some point after the e-mail has been created/sent.

**Comment by trisdoan** [comment]
Thanks guys for your report, fixed in [15.0](https://github.com/OCA/social/pull/1309) and [16.0](https://github.com/OCA/social/pull/1310), would you mind reviewing?
