### ISSUE TITLE
[16.0] python library dependency conflict 'pyparsing' (social/server-ux)

### ISSUE THREAD

**Issue by CRogos** [OCA/social#1316]
## Module
mail_drop_target
https://github.com/OCA/social/pull/1217

## Describe the bug
I am running Odoo in odoo.sh and since the PR above, I get a dependency version conflict which is originally caused by **extract_msg** . Does anyone have similar issues or an idea how so solve this?

```
2024-02-23T17:27:27,474 ERROR: Cannot install -r /home/odoo/.requirements.txt (line 14) and RTFDE because these package versions have conflicting dependencies.
2024-02-23T17:27:27,474 
2024-02-23T17:27:27,474 The conflict is caused by:
2024-02-23T17:27:27,474     pyrfc6266 1.0.0 depends on pyparsing~=3.0.7
2024-02-23T17:27:27,474     oletools 0.60.1 depends on pyparsing<3 and >=2.1.0
```

## To Reproduce
I am not using this module, but having extract_msg in the requirements.txt is enough to get startup errors.

**Comment by uvid-sinisa** [comment]
I have the same problem on odoo.sh. Specifically, these two seem to be in conflict:

social/mail_drop_target
Python dependency: extract_msg -> RTFDE -> oletools -> pyparsing (< 3,>=2.1.0)

server-ux/base_binary_url_import 
Python dependency: pyrfc6266 -> pyparsing (~=3.0.7)

**Comment by CRogos** [comment]
This could fix the issue... 
https://github.com/decalage2/oletools/pull/812

... or mail_drop_target needs to remove the dependency of extract_msg

**Comment by gbtechnology** [comment]
@CRogos unfortunately that won't solve the issue.
pyrfc6266 1.0.0 depends on pyparsing~=3.0.7
oletools 0.60.1 depends on pyparsing<3 and >=2.1.0

By odoo.sh logs it seems that pyrfc6266 1.0.0 wants a pyparsing version greater of the ones wanted by oletools. This is very annoying, as it is blocking social repository deployment

**Comment by CRogos** [comment]
@gbtechnology from my point of view, we need a new version of oletools, which depends on pypasing > 3.0.0 which is currently not available. But the linked PR would archive this. 

The most annoying thing is, that I do not need the module which adds the oletools dependency. But because all dependencies are automatically added to the requirements.txt and all requirements.txt are automatically aggregated/installed by odoo.sh this dependency causes the block. 

When adding OCA repositories as submodules to odoo.sh projects, this can also cause updates of libraries which might not be compatible with some odoo core functions. (recently happened to me with lxml and also pikepdf) 

Currently I see only the option to fork the repository and create a new branch, that remove the requirements.txt or at least the unneeded libs.

there is also a good thread on these kind of topic here: https://github.com/OCA/queue/pull/530

**Comment by ramiadavid** [comment]
@CRogos @gbtechnology 

And we couldn't just remove the dependency pyrfc6266? is only used for the base_binary_url_import module and only in one place a single function to extract a file name from http response, we could try to replicate that behavior without using the module, right?

https://github.com/OCA/server-ux/blob/42fac842508cb17364a1105398756bc69037e8bb/base_binary_url_import/wizard/base_binary_url_import.py#L320-L322

**Comment by CRogos** [comment]
yes also a good option... for both modules/libraries.
Nevertheless it is a pity that we cannot add social + server-ux at the same time in odoo.sh eventhough we are not installing the incompatible modules.

**Comment by ramiadavid** [comment]
@CRogos @gbtechnology 
I have uploaded a PR with a proposed solution, what do you think?

**Comment by CRogos** [comment]
I don't think adding a copy of the library is a good solution. 
The patch for oletools is already applied but there is no new version build yet.
Is there a possibility to install oletools from the github repo main branch, instead of pip?

**Comment by CRogos** [comment]
A new version oletools 0.60.2 is now available which solves the conflict.
