### ISSUE TITLE
mail_activity_done: wrong counters

### ISSUE THREAD

**Issue by gurneyalex** [OCA/social#1327]
When using the mail_activity_done module the counters are not correctly computed

The module overrides res.users::systray_get_activities which is used to gather the information displayed in the systray. 

It calls super().systray_get_activities which will compute the counters for all the activities (including the ones in state 'done', which are archived when this module is installed, but removed in a normal implementation) and then tries to compute the number of done activities and to substract that quantity from the counters computed by super(). 

The problem is that the counters are aggregated by models : one counter for crm.lead, one for sale.orders, and the counter is not a counter of activities, but a counter of records of said model which have late activities, activities for today and activities in the future, so bluntly substracting is wrong. 

## To Reproduce
affected versions 16.0 for sure, but probably all others too. 

1. remove all activities assigned to user1 from the database (deletion, not flagging as done)
2. Create a crm.lead with activities assigned to the same user, scheduled 10 days in the past
3. flag one activity as done
4. log in as the user, and check the activities systray

**Expected behavior**

The counter for late activities is 1

**Actual behavior**

The counter for late activities is 0

**Comment by navarrorico** [comment]
This bug is not fixed yet. How can we reopen?
