### ISSUE TITLE
[16.0] mail_gateway_whatsapp unable to send messages to client

### ISSUE THREAD

**Issue by augustodinizl** [OCA/social#1373]
Sending message to whatsapp returns 200, but the message never arrives tos the destination

## Module
The name of the module that has a bug.
mail_gateway_whatsapp
## Describe the bug

The issue was reported several times before, the complete tracklog can be seen here #1305 

## To Reproduce
**Affected versions**:
16.0
1. Follow the instructions to install and setup the module
2.Receive a message
3.Try to send a message

**Expected behavior**
the message should arrive at the client, since i got the 200 message from the whatsapp server.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
@etobella , i'm opening that issue, to keep the follow-up from the previous conversation... maybe that print can help somehow, since i don't know what to do next...
![image](https://github.com/OCA/social/assets/25938418/f2ecb96f-3dc7-4fb8-a1e1-b6dd45d27c35)

![image](https://github.com/OCA/social/assets/25938418/817bedaf-0cc3-4446-8e11-de598c88e036)

**Comment by augustodinizl** [comment]
@etobella , i found the "missing part"for it to work here, i had to enable that part 
![image](https://github.com/OCA/social/assets/25938418/f9dbf756-26cb-4673-a38a-ac1c413f9da4)

Thank you for your awesome work man!!!!!

**Comment by etobella** [comment]
Good to hear, I was worried about your issue :cry: 

So happy that it is solved :tada:
