### ISSUE TITLE
[10.0] RFC: Mass Mailing Theme Boilerplate (Community)

### ISSUE THREAD

**Issue by lukebranch** [OCA/social#139]
I've written a mass mailing theme template:

https://github.com/OdooCommunityWidgets/mass_mailing_themes_boilerplate

based on the default (community) mass mailing theme here:

https://github.com/odoo/odoo/blob/10.0/addons/mass_mailing/views/snippets_themes.xml

The template is still very much a work in progress, however it provides a boilerplate for others to customise and built their own mass mailing themes on top of. 

I am planning on adding more themes to the project as standalone modules under mass_mailing_themes_*, inside the mass_mailing_themes_boilerplate repository in the future as well.

Would this type of project be accepted into the OCA, and is this the right repository to submit a PR to when it's ready for review?

**Comment by rafaelbn** [comment]
@Yajo @pedrobaeza @sergio-teruel this could be interesting eventhough we work in v9 in this moment

**Comment by yajo** [comment]
Template is in https://github.com/OCA/maintainer-tools/tree/master/template/module, please open PR there adding missing files. Ping me when you do, thanks!

**Comment by pedrobaeza** [comment]
@Yajo

**Comment by pedrobaeza** [comment]
@Yajo, you have closed it very quick. Please read again the RFC. It's nothing to do with the README template.

**Comment by yajo** [comment]
Sorry, is this a real addon? Or is it just a template for mass mailing themes?

**Comment by lukebranch** [comment]
@Yajo ,

The module will be a mass mailing theme in a standalone module (mass_mailing_themes_boilerplate) using a best-practices approach for the basic theme template to act as a framework for others to build their own custom mass mailing themes on top of. In it's current state it is still very much a WIP, I just wanted to get some feedback before going much further.

I am also planning on expanding this into a set of modules later to include other themes as well (mass_mailing_themes_*), adding a variety of mass mailing template modules (or rolling them into a single module, whatever is preferred by the OCA).

Is this the correct repo to submit a PR to, or should I target maintainer-tools instead?

**Comment by yajo** [comment]
Then this is the right repo, I misunderstood, sorry 😞 

Please open WIP PR and let's review there 😊 

Thanks!

**Comment by lukebranch** [comment]
@Yajo ,

Ok, brilliant, thanks! I'll ping you all once I have a PR ready for review.
