### ISSUE TITLE
[16.0] mail_optional_follower_notification: ASCII character hidden in French translation.

### ISSUE THREAD

**Issue by DorianMAG** [OCA/social#1447]
## Module
mail_optional_follower_notification

## Describe the bug
When the French language is selected in the parameters, 
an error occurs when opening the popup for editing emails (mail.compose.message), 
when the module "mail_optional_follower_notification" is active.

## To Reproduce
**Affected versions**: 16.0

1. Open a fresh runboat
2. Verify the installation of the module mail_optional_follower_notification, otherwise install it
3. Modify the general settings to install the French language
4. Go to any chatter and open the editing of sending an email
5. Observe the error

**Expected behavior**
Open the editing of sending an email

![image](https://github.com/user-attachments/assets/e9f08b55-98d8-4eee-a598-b83a0d0e941d)
![image](https://github.com/user-attachments/assets/2f1de8d0-13c9-4fbe-95d8-e4529ce62be8)
![image](https://github.com/user-attachments/assets/1bf390ce-c834-4853-add4-c836c71a0621)

**Comment by quoc-pn** [comment]
@remi-filament

**Comment by remi-filament** [comment]
Thanks for pinging me on that issue.
I get a warning in weblate when I do not add this spaces, which I should try to fix in configuration, but anyhow this should be solved with https://github.com/OCA/social/commit/92640d7d282f251576e76b00e8b77d3e3cf8e598

Let me know if this is not the case @DorianMAG 
Best Regards,

**Comment by DorianMAG** [comment]
Hello, thank you for the feedback and fix. 
I'll test it and close the issue ticket based on the result. 
Regards

**Comment by DorianMAG** [comment]
Hello,
After testing on RunBoat, 
it seems to work normally! 
Thank you again
