### ISSUE TITLE
[8.0-mail_mandrill] Mandrill future ?

### ISSUE THREAD

**Issue by cvinh** [OCA/social#145]
Hello @rafaelbn @antespi 
I'm sorry to ask that question here because it's not an issue...
Since Mandrill dramatically increased their prices in april 2016, do you plan to develop a new module for another platform ? (sendinblue, mailjet, sendgrid... or else)
Thanks in advance for your reply
Cyril

**Comment by rafaelbn** [comment]
We did! https://github.com/OCA/social/tree/8.0/mail_tracking_mailgun 😄

**Comment by cvinh** [comment]
Thanks !!
