### ISSUE TITLE
Problems with character encoding

### ISSUE THREAD

**Issue by tpxxx** [OCA/social#153]
module: email_template_qweb
version: 10.0

**Steps to reproduce**
insert some non standard characters like äöü into the qweb e-mail template code, e.g.

`<t t-name="email_template_qweb.view_email_template_demo1">
        
        <t t-call="email_template_qweb.view_email_template_corporate_identity">
            
            <t t-set="email_heading" t-value="email_template.subject"/>
            <h2>Dear <t t-esc="object.name"/>,</h2>
            <p>
                This is an email template using qweb.
                öäüÖÄÜ
            </p>
        </t>
    </t>`

Then click the preview button to preview the template. 
- ...

**Current behavior**
The characters are shown as 

This is an email template using qweb. Ã¶Ã¤Ã¼Ã–Ã„Ãœ 

**Expected behavior**
The characters are shown as 

This is an email template using qweb. öäüÖÄÜ

The same behaviour is also observed, when the special characters are not directly written into the template code but stem from some database fields like company.name

**Comment by pedrobaeza** [comment]
Unfortunately your characters are also not shown in GitHub issue (at least not for me), so please change the text to be visible. Anyway, I think is something not with the module, but with QWeb, or the use you are making of it. If you get these characters working in for example a QWeb report, but not here, then it's an issue with this module.

**Comment by tpxxx** [comment]
Hello,

thank you very much for the quick answer. I made a screen shot of my original comment, which should now show all characters:
![grafik](https://cloud.githubusercontent.com/assets/26045700/23342763/5bf9d832-fc60-11e6-8704-11cb23099372.png)

Concerning the QWeb reports, everything works fine, i.e. all characters are shown as expected. The problem only shows up when using QWeb as email template with the email_template_qweb module

**Comment by pedrobaeza** [comment]
Well, the characters then seems to be the same (I was expecting other characters like japanese, chinese or similar). I'm from Spain, and I remember to apply several patches for making this work with accented characters and the Ñ character, but now it should be working. Check https://github.com/OCA/social/commit/09f821931aa346018abf6c2a76212bb8730d10f7 and https://github.com/OCA/social/commit/5d2a3bd93b71a162d0c65268eb68d04451d318d7 and apply them to 10.0. You can make a PR with them.

**Comment by tpxxx** [comment]
I applied both fixes and now everything works fine. Thank you very much!

**Comment by pedrobaeza** [comment]
Please make the PR for amending this for all.
