### ISSUE TITLE
[8.0] mail_debrand not working

### ISSUE THREAD

**Issue by jcdrubay** [OCA/social#160]
I tried to use mail debrand locally and it did not work for me, the last line mentioning about Odoo was still appearing.

I looked at the code and I did not understand how it could work.

mail_debrand seems to override the function `get_signature_footer` from `odoo/addons/mail`, but the function has a wrong name (extra `_` as first character) to override: `_get_signature_footer` instead of `get_signature_footer`.

Related source code:
 - https://github.com/odoo/odoo/blob/8.0/addons/mail/mail_followers.py#L138
 - https://github.com/OCA/social/blob/8.0/mail_debrand/models/mail.py#L12

I can submit a PR for this tiny fix if somebody could confirm that their is actually a problem (I did not succeed to perform a meaningful test to reproduce on Runbot).

**Comment by pedrobaeza** [comment]
Maybe it has been a renaming in Odoo... Please make the PR

**Comment by diggy128** [comment]
I can also verify the issue.
Removing _ from the function name resolves the issue.

**Comment by pedrobaeza** [comment]
Please make the PR

**Comment by diggy128** [comment]
Done #176

**Comment by pedrobaeza** [comment]
Fixed in #209
