### ISSUE TITLE
[RFC] mail_followup: Abstract Followup Messaging

### ISSUE THREAD

**Issue by lasley** [OCA/social#165]
This module will allow for customizable outbound emails for any record. A few use cases are for medical appointments (what to bring, arrive early, etc), car repair (notice of warranty and rights), and just simple sales followups. 

It will add a new model `mail.followup`, which will:
* Allow for you to choose a model to operate on
* Allow for you to choose a domain filter for records to match (similar to server actions)
* Allow for you to choose fields to group notifications by
* Allow you to select a `mail.template` for use
* Allow you to select the field on the model representing the partner to send the notification to

Security to this new model will be restricted to Administrators only. Contextual modules can then be created to override this if wanted, such as if Sales reps need to configure messages for Sales.

A new scheduled task will be added that will iterate the active `mail.followup` records, search for the filter, then send the mail.

The records matched in the filter will be grouped by the defined fields, then the groups will be iterated - with the recordset provided to the `mail.template` as `object`.

A default mail template will be provided, but it will be pretty basic and will mostly be to outline how to create custom templates.

This somewhat overlaps with https://github.com/OCA/product-attribute/issues/253, which will likely just use this module as a base. I didn't quite realize the overlap until after I abstracted out some other requirements 🚀 

Anyone know of anything similar we can base on? I know this is technically possible with Server Actions, but we need something a bit more contextual due to the amount of notifications that are needed.

**Comment by pedrobaeza** [comment]
Isn't better to add to the mass mailing module the periodicity feature? The rest is already there.

**Comment by lasley** [comment]
@pedrobaeza well now that's an interesting take on it, which I think could work well. There's still some missing pieces, but I absolutely love the features we would gain by going this direction. I haven't used the Mass Mailing module much, so apologies if these questions are stupid.

Would each email type be considered a "campaign" basically? So in the instance of event reminders, there would be an "Event Reminder" campaign that represents all of event reminders the system has sent so far.

If that's the case, I think we'll maybe need to make another view with some sort of flag for the actual mass mailings vs the follow-up mailings. We can then restrict the "Follow-up Mailings" and "Mass Mailings" views to show only the proper records.

Do you have any idea offhand if the `Retry` feature of Mass Mailings will resend to customers that have already received the email? I feel like it shouldn't, but I also don't see anything specifically handling it in the code either.
