### ISSUE TITLE
[RFC] mail_thread_recursive: Multiple threads per record

### ISSUE THREAD

**Issue by lasley** [OCA/social#175]
This module will provide the ability for true threaded conversations on Odoo models. In the current implementation of `mail.thread`, a record is considered to have one thread & is therefore considered one discussion. In some contexts, however, multiple independent discussions may be occurring - all with their own context and followers. 

An example of this is a blog, such as [this article](https://blog.laslabs.com/2013/01/pxe-server-ubuntu/), which contains numerous independent conversations regarding different aspects of the article. Each person that commented on the article could care less about the other comments on the article, but they also want to receive notifications for replies to their comment.

To be honest I have absolutely no idea where to begin here, so for a first time ever - I am submitting a blank RFC & am hoping that someone has an idea. I'll keep pondering as well, and update this if I come up with something substantial. 

Following are the high level requirements:
* Creating a new message in a record should create an entirely new `mail.thread` associated to the record
* All `mail.threads` associated to the record should be displayed in reverse chronological order (of last message received)
  * All messages of the `mail.thread` should be grouped together (think of email conversation view)
  * `mail.thread` views should be collapsible. 
* Following the record will follow all `mail.thread`s for the record
* `mail.thread` operation should not be changed
* Logic is required to catch the calls to all message functions at the record level & perform recursive actions instead

I'm thinking we can accomplish this view-side by simply iterating the `mail.thread` widgets. The real stumpers are:
* What to encapsulate the `mail.thread`s in
* How to override the `mail.thread` functionality from models already implementing that functionality, providing both the recursive and the regular threads (a regular thread would just be treated in the same way as the recursive I'm thinking)

So yeah as I said, this is a totally rough sketch. Anyone have some pointers or existing code?

**Comment by lukebranch** [comment]
I've come across this need a number of times, it's definitely something that would be very useful for Odoo.

I've seen a rough implementation of this concept in Slack:

<img src="https://user-images.githubusercontent.com/2337666/27507040-9b5855c6-58f9-11e7-8f9f-25909047fcb3.png" />

I don't have anything useful to add to the discussion at this point in time, however i'll comment back if I come up with some ideas.

**Comment by hbrunn** [comment]
I'm also petting with such an idea for a while, also without tangible results yet. What I can throw in however is this: Add a model `mail.category` (or call it label/thread or whatever) that defines possible categories (labels/threads) on messages for some model(s) or all. Then we define some rules like that a reply inherits the categories of its parent message. This way, we can categorize messages actually in multiple threads and the thread widget would then take care of sorting and showing messages by category/label/thread, with the possibility to add a message to multiple categories/labels/threads.
