### ISSUE TITLE
[9.0][10.0] mail_notify_exclude_notification

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/social#183]
I would like to propose to migrate to OCA part of the module from @alexis-via, 
https://github.com/akretion/odoo-usability/blob/10.0/mail_usability/mail.py, that deals with allowing users to choose if they want to exclude the partner from receving notifcations (e.g. invoice created, etc.).

We will add some test cases.

**Comment by JordiBForgeFlow** [comment]
cc @mreficent, @lreficent

**Comment by hbrunn** [comment]
Isn't this a less powerful version of https://github.com/OCA/social/tree/8.0/mail_follower_custom_notification ?

**Comment by yostashiro** [comment]
Another simple example around email notification although the requirement behind may not be so generic: https://github.com/rfhk/cip-custom/tree/10.0/mail_force_email

**Comment by LoisRForgeFlow** [comment]
@hbrunn could be but this module fix exactly our requirement.

@alexis-via are you ok with the migration to OCA?
