### ISSUE TITLE
[RFC] mail_outbound_static: Email FROM Headers

### ISSUE THREAD

**Issue by lasley** [OCA/social#194]
This module will allow you to configure the FROM header for any outbound email server, overriding the default operation of using the partner's email address in the FROM header.

The reasoning behind this is because manipulation of the FROM header is exactly what spammers do, and is called [email spoofing](http://searchsecurity.techtarget.com/definition/email-spoofing). This is why all of my emails to Odoo Community mailing lists go to SPAM, and this is why Odoo is not compatible with Amazon SES.

For anyone interested in email spoofing, particularly those of you who have email on your own domain and are not going to people's spam, I recommend you read [this article](https://www.digitalocean.com/community/tutorials/how-to-use-an-spf-record-to-prevent-spoofing-improve-e-mail-reliability) and implement.

Simple enough of a goal here - was just wondering if anyone knows of something pre-existing that we can base on for this?

**Comment by lasley** [comment]
cc @gdgellatly

**Comment by gdgellatly** [comment]
@lasley my own solution is to use my personal email address rather than
work ones.

One possibility i can think of is a secondary partner domain. Either a
subdomain or completely different which is automatically used when an email
address is not the main domain.

But more simply, why not just use the reply to as the from when domain
doesn't match and just manipulate the extra parts of the from header., E.g <
list@odoo.com> Odoo list (on behalf of x@x)

**Comment by gdgellatly** [comment]
Or actually, what GitHub does is perfect

**Comment by lasley** [comment]
> my own solution is to use my personal email address rather than
work ones.

Even my personal emails are on my own domain, so I'm screwed here.

> One possibility i can think of is a secondary partner domain. Either a
subdomain or completely different which is automatically used when an email
address is not the main domain.
> 
> But more simply, why not just use the reply to as the from when domain
doesn't match and just manipulate the extra parts of the from header., E.g <
list@odoo.com> Odoo list (on behalf of x@x)

With SES, you have to verify each outbound email address individually. Any sort of FROM header manipulation outside of a standardized email causes major scaling issues.

I'm not sure why Odoo chose header manipulation here, but this module will basically imitate the way that other true Enterprise products handle the email. The FROM Header will be defined in a configuration, the REPLY-TO as well. The only thing that should change is the Canonical From name in the header.

> Or actually, what GitHub does is perfect


Yup exactly. This is what I'm shooting for.

**Comment by gdgellatly** [comment]
There are 2 cases I think. Mail from domain users. We handle this by using
an authenticated IP specific mail relay to a whitelisted corporate mail
server.

So user Bob emails partner x a quote.

In that case from header manipulation is ok or even desirable.

Everything else, I agree, there's no point to manipulating it. In fact,
when you look at smart inboxes these days, e.g automatically labelled in
OCA/social it's probably better not to.

**Comment by lasley** [comment]
Closing to track in PR #195
