### ISSUE TITLE
"Click here to see mail content" module?

### ISSUE THREAD

**Issue by yajo** [OCA/social#21]
Does anybody know if there is any module that adds functionality of displaying a mass mailing in a web page in case somebody cannot read it right in the mailing client?

**Comment by rafaelbn** [comment]
If we would like any aproach to make this module we must ping!

cc @sergio-incaser @carlos-incaser @antespi @pedrobaeza

**Comment by pedrobaeza** [comment]
This feature is not available. As this doesn't contain any blueprint on how to implement it, I close the issue.
