### ISSUE TITLE
Backport of Odoo 11 mail_activy

### ISSUE THREAD

**Issue by sbidoul** [OCA/social#229]
We are planning to do a simple backport of Odoo 11 mail_activity: https://github.com/odoo/odoo/blob/11.0/addons/mail/models/mail_activity.py

Our plan is to migrate the models and see if we can do a simpler UI, perhaps in a notebook page you can mix-in in the views.

Our target is 9.0.

Is there any other effort in progress in this area, or other thoughts about this?

**Comment by hbrunn** [comment]
https://github.com/OCA/social/pull/204,version 10, but if we indeed don't do any heavy js-stuff the module should be pretty much the same for 9 and 10

**Comment by hbrunn** [comment]
I'd even be of a mind to have one addon for the data model, and one for the UI. In my current project, I'm only interested in the data model

**Comment by sbidoul** [comment]
Thanks for the pointer. How did I miss it.

I also had this idea to do a different module for the UI.
