### ISSUE TITLE
10.0 [mass_mailing_partner] you need to make corrections to the code

### ISSUE THREAD

**Issue by collex100** [OCA/social#230]
In document mail_mass_mailing_contact.py, you need to replace the line:
`list_id = vals.get('list_id', self.list_id.id)`
on
`list_id = int(vals.get('list_id', self.list_id.id))`

**Comment by pedrobaeza** [comment]
No if you pass correctly the values.

**Comment by collex100** [comment]
Because of this value:
 `list_id = vals.get('list_id', self.list_id.id)` 
module **html_form_builder** can not make a record in the **module mail.mass_mailing.contact**.
I did not find another solution.

**Comment by pedrobaeza** [comment]
That should be an integer, not an string. And that module is not OCA (or the name is incorrect).

**Comment by collex100** [comment]
Module: https://www.odoo.com/apps/modules/10.0/html_form_builder/

**Comment by pedrobaeza** [comment]
As said, the problem is with that module.

**Comment by collex100** [comment]
Thanks for the answer.
