### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by keyman1986** [OCA/social#231]
I added the following into odoo system parameters:

![image](https://user-images.githubusercontent.com/10662093/36233926-93a344d4-11a5-11e8-9039-760e538c4b1b.png)

The keys and values didn't exist till I added them.  Am I missing something I can't get the webhooks to work, when I test them in Mailgun they all fail "Response: <type 'exceptions.Exception'>"

Thanks I am using Odoo 10 Enterprise

**Comment by pedrobaeza** [comment]
Incorrect Mailgun parameters.

**Comment by keyman1986** [comment]
Thanks,

Please elaborate. Am I setting them in an incorrect area or fashion?
