### ISSUE TITLE
[10.0] mail_debrand, text to match has changed

### ISSUE THREAD

**Issue by travish2** [OCA/social#241]
Emails in v10 are being sent with a "Powered by Odoo" branding instead of "using" and "Odoo"

Is it feasible to extend the module to remove both instances of "Powered by Odoo" and "Sent using Odoo"?

![image](https://user-images.githubusercontent.com/30615274/36956913-17b60584-2085-11e8-9031-b01d01c11309.png)

**Comment by pedrobaeza** [comment]
It hasn't changed, but this is another thing. It's used when you are assigned to something. You usually do this for your employees , so it's not as needed as the other one, but you can make a PR improving the module if you want. I think this is a mail template that you can change.

**Comment by travish2** [comment]
Hi pedrobaeza, thank you for your reply.

The "Powered by Odoo" is also showing up in invoices:
![image](https://user-images.githubusercontent.com/30615274/37002510-1373e34e-211e-11e8-8432-358ea121beab.png)

Thank you for the heads up on the template, I have removed it from there.

**Comment by pedrobaeza** [comment]
Yeah, as that are templates, you can manually change them. The module doesn't change that part.

**Comment by Manibandaru** [comment]
May i know ,how you have removed that "Powered by Odoo" in mail template.

Thanks in Advance.

**Comment by travish2** [comment]
Settings -> Technical -> Emails -> Templates

Use a filter to list all messages where Body contains "odoo"

Then you can edit the templates to remove it.

**Comment by genvagula** [comment]
@travish2 i cannot find the proper template by your instructions. there just not any that contains "odoo". could you revise your advise or give another one on how to remove the "Sent by /company/ using Odoo." part from the e-mails?

With many thanks
Gen

**Comment by travish2** [comment]
@genvagula You will want to use module mail_debrand for that

I had email templates with a different phrase that may have been a hold over from earlier versions

**Comment by genvagula** [comment]
thank you @travish2. I use v13 but I see that the module for this one is still under development and not very actively. So I just have to stick with that branding stuff, at least for now.
