### ISSUE TITLE
In local odoo working y en production nop

### ISSUE THREAD

**Issue by adrianlaraperez88** [OCA/social#275]
Local odoo 11 email gmail, default odoo.config

Production odoo 11 email goddady
Odoo conf:

db_name = production_demo_final_email_track
list_db = False

**Comment by pedrobaeza** [comment]
Sorry, but the information is not enough. What is not working?

**Comment by pedrobaeza** [comment]
And some stacktrace, errors...

**Comment by adrianlaraperez88** [comment]
These are images of each system the local and the production, one shows me the option and the other does not

Local:
![image](https://user-images.githubusercontent.com/19626181/40162148-f93d391c-5980-11e8-9fbd-8dfd1ac92667.png)

Production:
![image](https://user-images.githubusercontent.com/19626181/40162217-374bd1d2-5981-11e8-9eaa-a0f36d29299c.png)

**Comment by pedrobaeza** [comment]
I don't see any problem with this, and it seems out of scope of this repo. Closing.

**Comment by adrianlaraperez88** [comment]
It no send me option same in local odoo??Please helpme

**Comment by pedrobaeza** [comment]
This tracker is for gathering bugs on the code. For help, please ask on forums.

**Comment by adrianlaraperez88** [comment]
Sorry ok
