### ISSUE TITLE
[11.0][MAIL][ADD] New folder for messages read in DISCUSS.

### ISSUE THREAD

**Issue by dajuayen** [OCA/social#291]
Currently when a message arrives it appears in the INBOX folder. If a message is marked as read, the message disappears.

The objective is to be able to keep a history of the messages and have access to the messages read in a folder other than INBOX, called ARCHIVED, for example.

This will allow you to search and consult about old messages.

**Comment by pedrobaeza** [comment]
Yeah, this can be very interesting. @gurneyalex and @simahawk I think you can be very interested in this.

**Comment by ghost** [comment]
https://github.com/it-projects-llc/mail-addons a lot of good function like the describted are from this good guys

**Comment by dajuayen** [comment]
@Yajo I have a doubt in JS and you can guide me. 
The object 'mail.chat_manager' saves the channels of the messaging in the variable 'channels' declared in the following way outside the class itself:
https://github.com/odoo/odoo/blob/bab5ccfdd7bd2138eb41db325981dc47641678f9/addons/mail/static/src/js/chat_manager.js#L25
In addition some functions that are not accessible.

I want to add another channel for the messages read, but that I know ChatManager does offer me a method to insert it. Should I overwrite the entire class by adding variables and functions?

**Comment by yajo** [comment]
I recommend you to avoid doing that. Read [the public interface](https://github.com/odoo/odoo/blob/bab5ccfdd7bd2138eb41db325981dc47641678f9/addons/mail/static/src/js/chat_manager.js#L626-L1272) and use it, it has methods such as `post_message`, `get_message`, `get_channel`, `create_channel`, etc., that usually should be enough for you.
