### ISSUE TITLE
[11.0] mail_tracking: compute email_score field take a lot of time when partner has a lot of mail.tracking.email records

### ISSUE THREAD

**Issue by zaoral** [OCA/social#298]
This is happening for the change made in email_is_bounced and email_score_from_email methods,
in version 9.0 we were filtering the last 10 records, while in version 11.0 we are searching in all the "mail.tracking.email" records. Visual diff bellow.

Does we need actually search in all the mail.tracking.email that exists? Maybe we could filter the last N records making N customizable by the admin user. Or have a ir.cron that clean  the records that we are not consulting since they are very old.

![diff-9-11-mail_tracking](https://user-images.githubusercontent.com/7593953/44995247-a2f98d00-af78-11e8-8f5a-7039c4bd8fd1.png)

**Comment by pedrobaeza** [comment]
This has been done for more accuracy, but you can improve the implementation:

* Change `search_count` by `search`
* Try to implement `read_group` when possible.

**Comment by chienandalu** [comment]
Hi, @zaoral . Can you review this related PR https://github.com/OCA/social/pull/299?

**Comment by pedrobaeza** [comment]
Fixed.

**Comment by zaoral** [comment]
Thank you @chienandalu @pedrobaeza 

I have tested with the fix you suggest/made and works.
Now it takes 83% less of time to compute email score.

Best Regards
