### ISSUE TITLE
[11.0][mail_tracking] User with Technical settings (group_no_one) cannot display email messages

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/social#314]
When a user has the debug mode (Technical Settings) activated they cannot display the mails associated to mail tracking, due to a permissions issue. Only users in group Administration/Settings  can access to object mail.tracking.value.

It is very common for certain users to have the technical settings (base.group_no_one) activated. 

IMHO the root cause of the problem is that mail_tracking provides the ability for any user to access emails. tracking values associated to mail.message should only be accessible by Administrator/Settings users, not by 'base.group_no_one'.

I have reported the issue to odoo https://github.com/odoo/odoo/issues/28340

But in a sense, the emails are not offered for display to users except on this module.

Perhaps the module should add groups='base.group_system' to https://github.com/odoo/odoo/blob/11.0/addons/mail/views/mail_message_views.xml#L82

**Comment by JordiBForgeFlow** [comment]
@rafaelbn @pedrobaeza  what do you think?

**Comment by pedrobaeza** [comment]
I don't get the problem: we are using this module in all our customers, and they have the group no_one activated (thanks to `base_technical_features`), and it's working without problems.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza Are you sure? Try to navigate to the actual mail.message, to display the message contents. It makes no sense that anyone could access, due to this:
https://github.com/odoo/odoo/blob/11.0/addons/mail/security/ir.model.access.csv#L28
https://github.com/odoo/odoo/blob/11.0/addons/mail/views/mail_message_views.xml#L83

Most probably your users are not jumping to the actual mail.message

**Comment by rafaelbn** [comment]
@jbeficent from where? I can try to reproduce

> When a user has the debug mode (Technical Settings) activated they cannot display the mails associated to mail tracking, due to a permissions issue.

**Comment by JordiBForgeFlow** [comment]
@rafaelbn So, as a user without 'Administration/Settings' permissions, go to a partner that has emails sent, press the button to display the mails
![image](https://user-images.githubusercontent.com/7683926/48190800-db846100-e343-11e8-8624-c40db8287c9d.png)

Then go to one of the emails sent, and click on the field 'Message' to navigate to the actual mail.message. 
It gives you a permissions error.
