### ISSUE TITLE
MailGun - Deliver _ BadRequest

### ISSUE THREAD

**Issue by AdegasOpencloud** [OCA/social#316]
Hi,
I am trying to configure Odoo to recive e-mail information from mailgun.

I configured the odoo parameters according and i configure the domain in mailgun, but when i am trying in webhooks separator do a test, i recive BadRequest as a response.

Event Type :Delivered Message
URL to test: https://<your_domain>/mail/tracking/all/<your_database>

I think the problem is that lib http.py from odoo expects post parameters inthe httprequest and they dont exist in the request coming from mailgun.

Any ideia?
Thanks.

**Comment by pedrobaeza** [comment]
This is for sending mails, not receiving, and the error is clear as you haven't put your specific data in the URL to test.
