### ISSUE TITLE
Mail verification

### ISSUE THREAD

**Issue by ghost** [OCA/social#327]
I need a module for the verification of email registration in newsletters. I let this module developed by my partners and it should be available in OCA.

This procedure is necessary after GDPR. Email-Verification would also be useful for the account registration and other parts of Odoo eg "follow the forum".

Is this the right place for this module? Its a good idea to develope this feature with focus to newsletter regitration or its better a more general approach (eg technical module for account-registration, newsletter-registration, following)

**Comment by pedrobaeza** [comment]
@Axel-G we talk a lot about this in my team and with Odoo, and the conclusion is that is the same sending first mail of the newsletter as acknowledge of the subscription and user unsubscribe from it than sending a non wanted email asking you for confirming that you want to subscribe, with the difference that the first one only requires one operation, and the other can hammer your inbox if done multiple times, so the conclusion is that is not needed and current situation is OK for GDPR.

**Comment by ghost** [comment]
I think its not only the problem of sending/getting emails. The emailadress is saved on odoo-system. For this act is a confirmation necassary. Without confirmation you have saved the adress illegal. If a adress is not confirmed you have to delete the record after a while (eg 24 hours). Its not ok that the emailowner is forced to act.

**Comment by pedrobaeza** [comment]
For that, we already have this module: https://github.com/OCA/data-protection/tree/10.0/privacy_consent

**Comment by ghost** [comment]
Thank you for your explanation. I dont know this module. I have to test it, thx.
