### ISSUE TITLE
[11.0] [mail_activity_board] restrict visibility on users to models in which they have permissions

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/social#335]
The board of activities is an interesting concept, but IMHO has a major drawback and itnis the security. Anyone can view all activities related to any object. 

But it makes more sense that sales looks at activities relating to leads and sales orders, but not purchase orders.

@Dajuayen @hbrunn do you thibk that it makes sense? Not sure of this is possible at all from a technical perspective. Would require to check the security on the object related to the activity

**Comment by hbrunn** [comment]
makes sense to me. But why isn't this already taken care of by https://github.com/OCA/OCB/blob/11.0/addons/mail/models/mail_activity.py#L154 ?

**Comment by dajuayen** [comment]
In relation to that from Sales where activities are controlled I will remember that the activities can also be related to other modules such as Project, so I think it makes sense that this activity board is independent.

**Comment by dajuayen** [comment]
@jbeficent @hbrunn are right, the question of security is not controlled in the module. Anyway @hbrunn makes a good contribution and it is possible that by going there, the problem could be controlled and that users see the right activities.

**Comment by JordiBForgeFlow** [comment]
@Dajuayen @hbrunn I checked and https://github.com/OCA/OCB/blob/11.0/addons/mail/models/mail_activity.py#L154 just takes care about write, create and unlink, not read.

@mreficent is working to fix also the read. Our idea is that when the _search method is called for mail.activities, and the list of activities is returned, we should then try to check permissions for each of the resources referenced by the activity, and return a subset of all the activities for which the user effectively has permissions. If we do this right, it should not have a performance impact.

**Comment by hbrunn** [comment]
this should more or less mimic what the model `mail.message` does. Look at how it's implemented there, it's complicated
