### ISSUE TITLE
Slow contact loading/saving when using Email Tracker

### ISSUE THREAD

**Issue by BigleafBrandon** [OCA/social#347]
We have been using your Email Tracking app in our v11 Odoo.sh hosted environment for several months. We love the functionality, however we were experiencing very slow opening/saving of contacts. We could see that there were 34k tracking emails and 19k tracking events. After uninstalling and reinstalling the app, the speed got much better, however, our tracking email and events tables were cleared with the uninstall. Our concern is if we keep using the app we’ll start seeing the same slowdowns as we get more emails into the system.

Is this a known issue? If so, is there any way to improve the speed without uninstalling/reinstalling the app?

**Comment by pedrobaeza** [comment]
Are you using latest code? Specifically the commit https://github.com/OCA/social/commit/361db616774137a6411407c3e6dcd6f7f8d2abc3#diff-57d7aee26e2837000c82f4673bd8dfb7 that improves the performance? We are using it with 376K tracked emails and 1.7M tracking events without performance problems.

**Comment by BigleafBrandon** [comment]
We have upgrade to the latest commit. No issues so far. Thanks!
