### ISSUE TITLE
mail_tracking

### ISSUE THREAD

**Issue by nch-odoo** [OCA/social#349]
Hi,

Installed mail_tracking in odoo 9 ..sent an email from chatter. The  email was received and opened in the external mail app(GMAIL). but the status of the mail tracker only shows as SENT. How does other states go on. I mean the other states does not change.

Am I missing something !

Thanks

**Comment by pedrobaeza** [comment]
This is due to:

* Your Odoo is not accessible to outside.
* Your dbfilter is not correct.
* Your web.base.url system parameter is not correct.

**Comment by nch-odoo** [comment]
Hi Pedro,

Thanks for  your reponse !

Can you ellobrate on the above points . What are expected settings to work.

PS: I am testing on local db. 

what extra settings needs to work for a multi db ?

**Comment by pedrobaeza** [comment]
Sorry, but this is out of the scope of this issue tracker and the module itself.
