### ISSUE TITLE
email deliverd status unreadeable

### ISSUE THREAD

**Issue by bullet92** [OCA/social#352]
Hi,
using mail_tracking I can't rtrack the state of the email: if there were an error on sending or anyother. The only thing that works is the opened state. The mail server supports this standard things, indeed if I send an email from the same outgoing address used in odoo, I receive an emails about the sent status: received from mx, user not exist, mail read and etc.
Could you help me to get the things working?

**Comment by pedrobaeza** [comment]
The module catches the events that are passed: received event can't be got by a traditional mailserver, but through hooks. And bounce notifications should be enabled on the mail server, which is not the usual case for avoiding spam. We use Mailgun as mail server for having full events.
