### ISSUE TITLE
Show done activities?

### ISSUE THREAD

**Issue by BigleafBrandon** [OCA/social#353]
module: mail_activity_board
version: 11.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by BigleafBrandon** [comment]
Is it possible to see closed/done activities? If so, how?

If not, woild you be able to customize the app to do so for a fee?

**Comment by LoisRForgeFlow** [comment]
I think this is exactly what you need: https://github.com/OCA/social/pull/296

**Comment by BigleafBrandon** [comment]
Pardon my ignorance, but I am unable to find the zip download for mail_activity_done. I downloaded both the v11 and v12 zip files but don’t see any reference to a mail_activity_done module.

Thank you for your help!

On Jan 14, 2019, at 1:18 AM, Lois Rilo <notifications@github.com> wrote:

I think this is exactly what you need: #296<https://github.com/OCA/social/pull/296>

**Comment by JordiBForgeFlow** [comment]
This work is in progress. In a few days it will be available for you to
download easily.

**Comment by BigleafBrandon** [comment]
Thanks!

**Comment by BigleafBrandon** [comment]
Any updates on this?

From: Brandon Smith
Sent: Thursday, January 17, 2019 8:10 PM
To: 'OCA/social' <reply@reply.github.com>
Subject: RE: [OCA/social] Show done activities? (#353)

Thanks!

**Comment by BigleafBrandon** [comment]
Any updates on this?

From: Brandon Smith
Sent: Thursday, January 17, 2019 8:10 PM
To: 'OCA/social' <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: RE: [OCA/social] Show done activities? (#353)

Thanks!

**Comment by JordiBForgeFlow** [comment]
@BigleafBrandon You can now download from https://github.com/OCA/social/archive/11.0.zip
