### ISSUE TITLE
[Question ] "sent by company" mail_debrand

### ISSUE THREAD

**Issue by taOsemc** [OCA/social#361]
Hi,

Fantastic module! 

I would like to know if it's possible to remove "Sent by company" as well. It's curretnly removing "by Odoo".

Thank you !
Jean-Philippe

**Comment by pedrobaeza** [comment]
That's another feature that is not debranding at all, and it's not included in the module.

**Comment by taOsemc** [comment]
Thank you for your answer @pedrobaeza
