### ISSUE TITLE
[11.0] Error in view mail_activity_views.xml

### ISSUE THREAD

**Issue by CarlesAntoli** [OCA/social#368]
Hi,
In the mail_activity_views.xml the domain is not correct

<attribute name = "domain"> [('activity_ids.date_deadline', '& gt;', context_today (). Strftime ('% Y-% m-% d')), ( 'done', '! =', True)] </ attribute>.

Should be:

                 <attribute name = "domain"> [('date_deadline', '&' ;, context_today (). strftime ('% Y-% m-% d')), ('done', '! =', True) ] </ attribute>

**Comment by pedrobaeza** [comment]
Which module? Which version?

**Comment by CarlesAntoli** [comment]
Sorry, module mail_activity_done version 11
