### ISSUE TITLE
travis & runbot fail on dependency clone

### ISSUE THREAD

**Issue by tbaden** [OCA/social#378]
in the oca_dependencies file is the line:
https://github.com/OCA/social/blob/66bb112d2f27b8fe902b352f89569782e043c6f3/oca_dependencies.txt#L3

but the branch no longer exists, which fails the runbot & travis checks

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/OCA/social/commit/a0bc66bb77727cd258ba76caeb408f3e43f5f6c9
