### ISSUE TITLE
[9.0][email_template_qweb] Export Po files: Sentences split at QWEB instruction

### ISSUE THREAD

**Issue by mehdi-ghezal** [OCA/social#383]
Hello,

I use **email_template_qweb** module in **Odoo 9** and I have an email template with the following simplified content.

<template id="notify_supplier_view">
    <t t-set="o" t-value="object.with_context({'lang': env.lang or 'fr_FR'})" />

    <t t-call="email_template_base_layout_view">
        <p>
            Please find the RFQ <t t-esc="o.name" /> in attachment of this email.
        </p>
    </t> 
</template>

When I export my PO files for translation, the sentence is split in two parts:
 - Please find the RFQ 
 - in attachment of this email.

So for the translation, I lose the context and the ability to change position of "o.name".

I'm wrong about something in my implementation ?
Or maybe this is a known issue of the module ?

Regards,

**Comment by pedrobaeza** [comment]
Sorry, this is how QWeb translations in Odoo works, so it's not something of the module, and it's not going to change also in Odoo, as it's the used method.

**Comment by mehdi-ghezal** [comment]
Oh yes you're right !
I didn't notice since today, for my report's it's the same.

Didn't got any case when I need the full context since today, so I'm gonna find a workaround, thank you for your reply Pedro :)
