### ISSUE TITLE
[11.0] mail_activity_done messes next activity date

### ISSUE THREAD

**Issue by aitorbouzas** [OCA/social#386]
Just tested this module. There's a small catch with it, I don't know if i'm not using it correctly...
In a `crm.lead` (that inherits from `mail.activity.mixin`) there's a problem with `activity_date_deadline` field. It doesn't show the next activity date, rather the first activity it encounters.

This field is defined such as:
```
    activity_date_deadline = fields.Date(
        'Next Activity Deadline', related='activity_ids.date_deadline',
        readonly=True, store=True,  # store to enable ordering + search
        groups="base.group_user")
```

Since with `mail_activity_done` the activity stays related to the record, this field will be showing incorrect information.

**Comment by emagdalenaC2i** [comment]
@aitorbouzas Please, take a look at #380

**Comment by aitorbouzas** [comment]
AFAIK that fix doesn't correct this behaviour. Am i missing something?

**Comment by emagdalenaC2i** [comment]
No, sorry. It is a different issue
