### ISSUE TITLE
[10.0] Should requeriments social have simplejson dependency?

### ISSUE THREAD

**Issue by igallart** [OCA/social#391]
When I have social in my repositories, it fail and it say:

social/mail_sendgrid/controllers/json_request.py

line 48, in _json_response
    body = simplejson.dumps(response)
NameError: global name 'simplejson' is not defined

I think that social requeriments should have simplejson.

**Comment by hbrunn** [comment]
since https://github.com/OCA/social/pull/372 this shouldn't be the case any more

**Comment by igallart** [comment]
Sorry, my source was outdated.
