### ISSUE TITLE
Doesn't work on Odoo Online

### ISSUE THREAD

**Issue by LiberTang0** [OCA/social#396]
Nothing happens with Odoo Online (V12)

**Comment by pedrobaeza** [comment]
Which module? Which problem?

**Comment by LiberTang0** [comment]
module: mail_debrand
problem: nothing happens

"sent using odoo" still present when sending a message from the CRM

**Comment by pedrobaeza** [comment]
Please use latest version that was merged yesterday.

**Comment by LiberTang0** [comment]
I test with the lastest version and doesn't work on odoo online, nothing happens

**Comment by pedrobaeza** [comment]
It should work the same in "Odoo online" (that I suppose it's odoo.sh). Try on the runbot link to check.

**Comment by LiberTang0** [comment]
Not odoo.sh, just odoo online, with the import module features

**Comment by pedrobaeza** [comment]
Then it's logical that it doesn't work. You can't import modules in odoo online that contains code. Only data modules. It's specified when uploading it AFAIK.

**Comment by marcozink** [comment]
Hey @LiberTang0, are you using Odoo in a language other than english? If you are, you need to add the translated string so the regex matches the email template, otherwise it will not work.
