### ISSUE TITLE
[RFC] implement matrix client-server api

### ISSUE THREAD

**Issue by hbrunn** [OCA/social#405]
I'm a fan of [matrix](https://matrix.org) and like the [riot](https://about.riot.im/) client quite a bit.

Lately, we replaced our internal chat with Odoo groups, and one thing that lacks is a nice open source mobile client for this. As I'm a better Odoo developer than mobile, I propose to not bother with a nice Odoo chat app at all, but support matrix' [client](https://matrix.org/docs/spec/client_server/r0.5.0) api. This is big, but doesn't seem impossible to me to do, and then we can just lift with matrix. So we'd have to write a bunch of controllers that map matrix events to messages, mail groups etc. But we don't need to support federation or identities, so I hope that implementing just a subset of the api will suffice to use riot as a mobile app for odoo chats

**Comment by hbrunn** [comment]
@ntsirintanis @thomaspaulb

**Comment by thomaspaulb** [comment]
I've been looking at making a [bridge](https://matrix.org/bridges). It [seemed](https://about.riot.im/why-riot) that this is the preferred way of coupling Riot to other chat networks:

> (...) Stop juggling different apps for different teams, suppliers and networks by bridging other services, like Slack and IRC. (...)

[This page](https://matrix.org/blog/2017/03/11/how-do-i-bridge-thee-let-me-count-the-ways) has a nice XKCD cartoon and an explanation about the different kinds of bridging.

However, for the preferred "puppeting" type of bridge, as I understand it, every user has to run his own Odoo bridge, which seems kind of overkill. Am not fully sure but basing myself on [this](https://github.com/matrix-hacks/matrix-puppet-bridge#q-is-this-made-to-handle-several-facebookhangoutsslack-users-within-one-bridge-in-other-words-can-i-use-this-for-mass-hosting-of-many-imessagefacebookhangouts-identities-with-one-matrix-homeserver).

So in that case your method could be easier and Odoo could be molded into a dumbed-down version of a homeserver that Riot.im can connect to. But it does require implementing a lot of endpoints.

Another option would be to just take one of the HTML/JS based Odoo-apps that we have built so far and hack a chat function into them.

Each option seems like a sizable amount of work..

**Comment by hbrunn** [comment]
Indeed, a lot of work. Another thing I'm looking into is making Odoo behave as a server against other servers. The protocol https://matrix.org/docs/spec/server_server/r0.1.2 at least has much less endpoints.

**Comment by deantheiceman** [comment]
What did you guys end up doing for this? @hbrunn @ThomasBinsfeld

**Comment by thomaspaulb** [comment]
@deantheiceman On our side we started on a Google Chrome app chat client, but never finished it:

https://github.com/sunflowerit/sfit-chat

**Comment by yajo** [comment]
I wouldn't waste time in making Odoo a matrix server, just go for the bridge. It's the way it has to be done, and it will provide the best integration experience with the least support surface.

OTOH, you can try to use https://delta.chat/ as a mail client for Odoo.

**Comment by marcos-mendez** [comment]
> I'm a fan of [matrix](https://matrix.org) and like the [riot](https://about.riot.im/) client quite a bit.
> 
> Lately, we replaced our internal chat with Odoo groups, and one thing that lacks is a nice open source mobile client for this. As I'm a better Odoo developer than mobile, I propose to not bother with a nice Odoo chat app at all, but support matrix' [client](https://matrix.org/docs/spec/client_server/r0.5.0) api. This is big, but doesn't seem impossible to me to do, and then we can just lift with matrix. So we'd have to write a bunch of controllers that map matrix events to messages, mail groups etc. But we don't need to support federation or identities, so I hope that implementing just a subset of the api will suffice to use riot as a mobile app for odoo chats

I've been developing a mobile interface that can use the odoo.mail xml-rpc, if you are interested please feel free to use it https://github.com/popsolutions/bailaki-app
