### ISSUE TITLE
Mail_tracking > Refresh status

### ISSUE THREAD

**Issue by gregory-moka** [OCA/social#409]
It seems that the traking status is not refreshed after sending. So, if user doesn't refresh the app (F5), tracking status will always be on "Unknown".
Is there a way to ensure user that the mail has been correctly sent without having to refresh page ?

**Comment by pedrobaeza** [comment]
No, you have to refresh manually, as automatic refreshing was deactivated by Odoo intentionally in v11, as it creates a lot of fake request on people leaving opened tabs.
