### ISSUE TITLE
Error Mailgun's mail tracking: receive JSON request instead of HTTP request

### ISSUE THREAD

**Issue by zaoral** [OCA/social#424]
Mailgun let us to inform via Webwook to an URL events like when a messages has been delivered, temporally_fail, permanente_fail, etc.

Odoo has a controller defined in **mail_tracking** module that let us to capture this information to update mail tracking information (**/mail/tracking/all/<db_name>**). This controller accept HTTP request, but it seams like Mailgun API has change and now is sending a JSON request instead of a HTTP request.

This is making that Odoo can not process the information about the messages status that mailgun is sending via Webhook. Here is an screenshot

```sh
2019-07-29 15:17:22,320 53 INFO adhoc odoo.http: <function MailTrackingController.mail_tracking_all at 0x7f4a5297f9d8>, /mail/tracking/all/adhoc: Function declared as capable of handling request of type 'http' but called with a request of type 'json'
2019-07-29 15:17:22,320 53 ERROR adhoc odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python3.5/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python3.5/dist-packages/odoo/http.py", line 320, in _call_function
    raise werkzeug.exceptions.BadRequest(msg % params)
werkzeug.exceptions.BadRequest: 400 Bad Request: <function MailTrackingController.mail_tracking_all at 0x7f4a5297f9d8>, /mail/tracking/all/adhoc: Function declared as capable of handling request of type 'http' but called with a request of type 'json'
2019-07-29 15:17:22,323 53 INFO adhoc werkzeug: 50.112.207.19 - - [29/Jul/2019 15:17:22] "POST /mail/t
```

If I use action_manual_check_mailgun method directly (Re-sync Mailgun button) it works. Maybe I miss a configuration?

@chienandalu @pedrobaeza Please could you confirm if this is also happening to you? 

Best Regards

**Comment by pedrobaeza** [comment]
No, we are using it without any problem in several customers. This seems another thing.

Closing while no further information is provided.

**Comment by zaoral** [comment]
@pedrobaeza  Please could you tell me if you are using Webhooks or Legacy Webkooks?

When I try to use Webhooks the error I mention occurs, If I use Legacy Webhooks this error does not appears.

**Comment by pedrobaeza** [comment]
@zaoral Indeed mine are legacy webhooks, as when I configured them, there was only that ones. I have accessed today to Mailgun control panel and discover the whole redesign and features they have added.

We can include a note about the webhook part on the README configuration part, and in the ROADMAP. Do you plan to provide compatibility with new webhooks?

**Comment by zaoral** [comment]
@pedrobaeza We will try to add compatibility to the new webhook API for version 12.0, but we estimate that we would start working on this just in a month or 2 because we are closing some projects.

Best Regards

**Comment by pedrobaeza** [comment]
OK, but is there any advantage of using these new webhooks?

**Comment by zaoral** [comment]
I have not tested yet, but I asked to mailgun support and they tell me:

> well eventually everyone is going to need to move off of the legacy webhooks (you will be notified 90 days in advance) so it's a question of if you want to do that now or if you want to wait until you "have" to. The new webhooks are easier to use, have push notifications, there are more analytics, they will have more information about the events. The legacy webhooks had unique formatting. The new webhooks match our events API It's more in line with our API so you can consume the information about the event better

**Comment by zaoral** [comment]
@pedrobaeza  I leave you here two PRs in order to review.

* updated the README of the module to indicate that it only works for legacy Webhooks https://github.com/OCA/social/pull/430
* I detect that for legacy wehooks we were missing to map some errors that Mailgun sent us, more information in https://github.com/OCA/social/pull/429

Best Regards

**Comment by pedrobaeza** [comment]
OK, thanks

**Comment by pedrobaeza** [comment]
The latest versions use the new API and auto populate the hook through a button.
