### ISSUE TITLE
[12.0] New Module: mail_notify

### ISSUE THREAD

**Issue by kh-badep** [OCA/social#425]
We have a new module that enables Push notifications for all incoming messages. By default, push notifications on Odoo are enabled only for chat. This module removes this restriction to enable push notifications on incoming messages (inbox) and activities. It also improves the notification by adding an URL to open the related document by clicking on the notification, the document icon or the sender avatar.

Another restriction on Odoo default implementations is that it relies on bus_bus to send notifications to the web client, which means that the user does not receive a notification if he doesn't have an open browser tab on Odoo. Even worse, due to memory management changes in modern browsers like Chrome (see: https://developers.google.com/web/updates/2015/09/tab-discarding), sometimes the tab will be put on "sleep" and therefore the client will not receive notifications. This module has also an option to rely on a service worker like FCM to deliver push notifications on the background. This also works like a charm on mobile phones.

Link to module: https://github.com/BADEP/addons/tree/12.0/mail_notify

**Comment by pedrobaeza** [comment]
Thanks for expressing your interest in bringing this to OCA. It seems an interesting module.

Let's see what people thinks about this.

**Comment by burhanghee** [comment]
@metamasterplay any plans to get this module ported to V.13??

**Comment by kh-badep** [comment]
Hello,
 A PR has been submitted here for v12: https://github.com/OCA/social/pull/568. I'll do another one for v13 once it's approved.

@pedrobaeza any tips on why or when the PR will be reviewed?

**Comment by augustodinizl** [comment]
@kh-badep do you still have plans to bring that module to OCA? yeah, i know that's 2 years later, BUT... 

it has an awesome use in v16, since @etobella launched the #1305 .
Any thoughts @pedrobaeza ?
