### ISSUE TITLE
High Level functionlity

### ISSUE THREAD

**Issue by chrizzTs** [OCA/social#426]
Dear all,
I really love this module!
I am just wondering if you could explain me how this generally works.

So how is this module collecting the status if it was opened? Is a link added to each mail via the template and it triggered by the user when it opens a mail.
Does it internaly then use the Odoo tracking links?

Would be great if some body could explain me the technical aspect how I can collect these information!
Thanks in advance!

**Comment by pedrobaeza** [comment]
Which module? Which Odoo version?
