### ISSUE TITLE
[12.0] mail_debrand: leaves a space before dot

### ISSUE THREAD

**Issue by Random-nobody** [OCA/social#427]
Mail debran version: 12.0.2.0.1

When emails are sent with footer like this:
`Sent by <company name> using Odoo.`
"_using Odoo_" is removed and there is an ugly space and dot after the company name:

![20190821_094701](https://user-images.githubusercontent.com/16503469/63413032-354ca800-c3f9-11e9-928d-801b30206655.png)

This is the responsible piece of code:
```python
html = re.sub(
           using_word + "(.*)[\r\n]*(.*)>" + odoo_word + r"</a>", "", html,
)
```
I coudn't find an easy way to remove the space - so I removed a dot by matching it in regex as well (and I think it is even prettier to not have a dot in the footer):
```python
html = re.sub(
           using_word + "(.*)[\r\n]*(.*)>" + odoo_word + r"</a>.", "", html,
)
```
And it looks like this:

![20190821_095923](https://user-images.githubusercontent.com/16503469/63413688-81e4b300-c3fa-11e9-8b86-9f2ad6af1158.png)

**Comment by pedrobaeza** [comment]
I prefer to leave the dot.
