### ISSUE TITLE
[11.0] mail_tracking: message_post signature changed

### ISSUE THREAD

**Issue by omar7r** [OCA/social#428]
Hi,

Recently was added to mail_tracking an inheritance of mail.thread (commit https://github.com/OCA/social/commit/8b89ab39be769bbd2f23824c2ea9f229a9e0dcc9#diff-0078a63221515aa79d9ca590dfd5d377). The method "mesage_post" was declared with *args, **kwargs and the default signature only has **kwargs, now it fails when pass as first argument to message_post the message without indicate that this argument is the body, for example in sale_stock on method _update_line_quantity call this methos without the key and it fails, maybe in more places.

@Tardo check this please, the commit is yours

**Comment by pedrobaeza** [comment]
Fixed directly in https://github.com/OCA/social/commit/f47ad8382491999b23ab2562443717b6c8efae0c. Thanks for reporting and good catch.
