### ISSUE TITLE
[11.0][mail_tracking] Incompatibility with OCB commit

### ISSUE THREAD

**Issue by oscars8a** [OCA/social#443]
https://github.com/OCA/social/blob/eeedcbd41dc960ffdf19e8f7924ecb5b7aa9d84d/mail_tracking/static/src/js/mail_tracking.js#L11

Hello,

I have a problem with the module mail_tracking in Odoo 11.0.

Two days ago I updated the repositories, and customers who have installed the mail_tracking module, they are having trouble creating activities. When I create an activity, until I refresh the page, the activity does not appear.

I think the module has some incompatibility with the latest OCB changes:
https://github.com/OCA/OCB/commit/d7623ddcfb886194c5501bc5db36360caed15da8
There are changes in the file chatter.js

If I uninstall mail_tracking the problem disappears

Thanks a lot.

**Comment by pedrobaeza** [comment]
@Tardo I was experimenting this also, but I thought it was the normal behavior in Odoo. Can you check in both 11 and 12?

**Comment by pedrobaeza** [comment]
Fixed in #446
