### ISSUE TITLE
Mail Tracking : Does not function with any other email client or browser except MACOS

### ISSUE THREAD

**Issue by AnilKesariya** [OCA/social#444]
I have installed the mail_tracking module and having a problem with acknowledgement part.

Like when somebody open an email which is not being tracked into the email tracker. It should be marked with double right sign according to the logic implemented and stated on screenshots and which works fine with MacOS mail client.

for e.g.

I have one test lead and having customer with email test.test@gmail.com

Now, the internal user is sending note to test customer by using chatter and when customer receive and open that email then right sign should appear twice, which state that email has been open by test user.

It is not working when email is being read on gmail account from any browser from any OS. and checked with few email client on linux too.

when the test user read/open an email from Mac OS then it works fine.

If this issue is already fixed by someone then I want to have the patch or correct me If I need to do some configuration to make this things work globally for all email client and browser from any OS.

Looking forward,

Best Regards,
Anil Kesariya

**Comment by pedrobaeza** [comment]
It's not a question of client not browser, but image blocking and your proxy deployment.

**Comment by AnilKesariya** [comment]
How can be that proxy deployment fix? any idea or suggestion can help. 

Thanks.
