### ISSUE TITLE
mass_mailing_partner installation error

### ISSUE THREAD

**Issue by chrizzTs** [OCA/social#465]
Hi all,
we have 107353 contacts in our system. When we are going to install mass_mailing_partner module, we have noticed that It is going to update partners records and we are facing below errors:

![image](https://user-images.githubusercontent.com/6087189/69095875-82213880-0a53-11ea-8846-157cac740549.png)
![image](https://user-images.githubusercontent.com/6087189/69095880-86e5ec80-0a53-11ea-98b1-26af6ee77637.png)
![image](https://user-images.githubusercontent.com/6087189/69095885-8a797380-0a53-11ea-960c-d0946315a9a4.png)
![image](https://user-images.githubusercontent.com/6087189/69095896-8fd6be00-0a53-11ea-8662-951725b47ebd.png)
![image](https://user-images.githubusercontent.com/6087189/69095912-95cc9f00-0a53-11ea-8056-09be1bcb081e.png)

For solving this issue we have also tried --limit-time-cpu=0 --limit-time-real=0 --limit-memory-soft=0 --max-cron-threads=0 commands but It is not resolving the issue.

Can you please guide us for it?
Thanks in advance!

**Comment by pedrobaeza** [comment]
@chienandalu any tip?

**Comment by chrizzTs** [comment]
@chienandalu any update on this?

**Comment by chienandalu** [comment]
I guess you've got a huge amount of registers to link so the init hook maybe should be optimized: https://github.com/OCA/social/blob/12.0/mass_mailing_partner/hooks.py#L13-L36

Maybe you can override it in your installation and pass the scripts manually in your instance.

**Comment by source-promo** [comment]
@chienandalu what is the init hook doing? 
Can I simply comment it out for installation? 
So only new contacts will be linked after installation?

**Comment by chienandalu** [comment]
That's it. Anyway, you can run the script by shell later
