### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by chrizzTs** [OCA/social#481]
I just tried to upgrade to the newest version on Github. But my build fails with followin error message:

Failed to load registry Traceback (most recent call last):   File "/home/odoo/src/odoo/odoo/modules/registry.py", line 86, in new     odoo.modules.load_modules(registry._db, force_demo, status, update_module)   File "/home/odoo/src/odoo/odoo/modules/loading.py", line 417, in load_modules     force, status, report, loaded_modules, update_module, models_to_check)   File "/home/odoo/src/odoo/odoo/modules/loading.py", line 313, in load_marked_modules     perform_checks=perform_checks, models_to_check=models_to_check   File "/home/odoo/src/odoo/odoo/modules/loading.py", line 227, in load_module_graph     migrations.migrate_module(package, 'post')   File "/home/odoo/src/odoo/odoo/modules/migration.py", line 181, in migrate_module     mod = load_script(pyfile, name)   File "/home/odoo/src/odoo/odoo/modules/migration.py", line 46, in load_script     spec.loader.exec_module(module)   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/home/odoo/src/user/oca-addons/mail_tracking/migrations/12.0.2.0.0/post-migrate.py", line 5, in <module>     from openupgradelib.openupgrade import migrate ModuleNotFoundError: No module named 'openupgradelib'
--

**Comment by pedrobaeza** [comment]
The error is clear: you need the Python library called openupgradelib. Install it.
