### ISSUE TITLE
[12.0][mail_tracking] many MailTracking email not found warnings

### ISSUE THREAD

**Issue by ruuter** [OCA/social#530]
This code snippet is polluting my logs with warning messages.

https://github.com/OCA/social/blob/8d985d8da9fa864113f87cd59a2b3173f7f89193/mail_tracking/controllers/main.py#L69-L78

How can this work if state will be marked 'opened' the first time? Each successive open will trigger above warning, because state is now 'opened' and will not match the above domain `('state', 'in', ['sent', 'delivered'])`.

 Is it intended to generate warnings each time mail is opened? Or what am I missing?

**Comment by pedrobaeza** [comment]
Indeed it seems something weird. Please open a PR doing the search without the state and having the warning if not found, but comparing later if in the required state for doing the call o the event create.
