### ISSUE TITLE
Issue during installation on Odoo.sh

### ISSUE THREAD

**Issue by syc-pad** [OCA/social#543]
Hello,

Your module seems very interesting, but I encountered troubles.

module: mail_tracking
version: 13.0

**Steps to reproduce**
- Install the module on Odoo.sh v13

**Current behavior**
These are error messages I received after the build on Odoo.sh :

Date | Level | Type | Message
-- | -- | -- | --
05/08/2020 18:49:21 | ERROR | server | Module web_mobile: 1 failures, 0 errors
05/08/2020 18:49:21 | ERROR | server | FAIL: MobileRoutesTest.test_database_list Traceback (most recent call last):   File "/home/odoo/src/enterprise/web_mobile/tests/test_mobile_routes.py", line 53, in test_database_list     self._is_success_json_response(data)   File "/home/odoo/src/enterprise/web_mobile/tests/test_mobile_routes.py", line 169, in _is_success_json_response     self.assertEqual(list(data.keys()), ["jsonrpc", "id", "result"], "should be a valid jsonrpc response") AssertionError: Lists differ: ['jsonrpc', 'id', 'error'] != ['jsonrpc', 'id', 'result']  First differing element 2: 'error' 'result'  - ['jsonrpc', 'id', 'error'] ?                     ^^^^  + ['jsonrpc', 'id', 'result'] ?                    + ^^^^  : should be a valid jsonrpc response
05/08/2020 18:49:21 | ERROR | server | Exception during JSON request handling. Traceback (most recent call last):   File "/home/odoo/src/odoo/odoo/http.py", line 624, in _handle_exception     return super(JsonRequest, self)._handle_exception(exception)   File "/home/odoo/src/odoo/odoo/http.py", line 310, in _handle_exception     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])   File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 14, in reraise     raise value   File "/home/odoo/src/odoo/odoo/http.py", line 669, in dispatch     result = self._call_function(**self.params)   File "/home/odoo/src/odoo/odoo/http.py", line 350, in _call_function     return checked_call(self.db, *args, **kwargs)   File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper     return f(dbname, *args, **kwargs)   File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call     result = self.endpoint(*a, **kw)   File "/home/odoo/src/odoo/odoo/http.py", line 915, in __call__     return self.method(*args, **kw)   File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap     response = f(*args, **kw)   File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1174, in list     return http.db_list()   File "/home/odoo/src/odoo/odoo/http.py", line 1473, in db_list     dbs = odoo.service.db.list_dbs(force)   File "/home/odoo/src/odoo/odoo/service/db.py", line 366, in list_dbs     raise odoo.exceptions.AccessDenied() odoo.exceptions.AccessDenied: Access denied
05/08/2020 18:49:20 | ERROR | server | Module web: 1 failures, 0 errors
05/08/2020 18:49:20 | ERROR | server | FAIL: WebSuite.test_js Traceback (most recent call last):   File "/home/odoo/src/odoo/addons/web/tests/test_js.py", line 15, in test_js     self.phantom_js('/web/tests?mod=web&failfast', "", "", login='admin', timeout=1800)   File "/home/odoo/src/odoo/odoo/tests/common.py", line 1226, in browser_js     self.fail('%s\n%s' % (message, error)) AssertionError: Some js test failed "QUnit test failed: "mail > Discuss (Moderation) > moderator: moderated channel with pending moderation message" [message: "the 'Unselect All' button should be disabled", actual: "false", expected: "true"] 1 / 10659 tests failed.
05/08/2020 18:46:28 | ERROR | server | Module base: 0 failures, 1 errors
05/08/2020 18:46:28 | ERROR | server | ERROR: TestFormCreate.test_create_res_partner Traceback (most recent call last):   File "/home/odoo/src/odoo/odoo/addons/base/tests/test_form_create.py", line 13, in test_create_res_partner     partner_form = Form(self.env['res.partner'])   File "/home/odoo/src/odoo/odoo/tests/common.py", line 1426, in __init__     self._process_fvg(recordp, fvg)   File "/home/odoo/src/odoo/odoo/tests/common.py", line 1512, in _process_fvg     fvg['onchange'] = model._onchange_spec(fvg)   File "/home/odoo/src/odoo/odoo/models.py", line 5859, in _onchange_spec     process(etree.fromstring(view_info['arch']), view_info, '')   File "/home/odoo/src/odoo/odoo/models.py", line 5855, in process     process(child, info, prefix)   File "/home/odoo/src/odoo/odoo/models.py", line 5855, in process     process(child, info, prefix)   File "/home/odoo/src/odoo/odoo/models.py", line 5851, in process     for subinfo in info['fields'][name].get('views', {}).values(): KeyError: 'failed_message_ids'
05/08/2020 18:46:19 | WARNING | server | MailTracking email '13' not found
05/08/2020 18:46:19 | WARNING | server | MailTracking email '12' not found
05/08/2020 18:46:19 | WARNING | server | MailTracking email '12' not found
05/08/2020 18:46:19 | WARNING | server | MailTracking email 'False' not found

**Expected behavior**
The build should happen seamless.

**Comment by pedrobaeza** [comment]
It seems incompatible with `web_mobile` enterprise module, but that out of scope of this. If you want to add compatibility, you can propose a PR in this repo.
