### ISSUE TITLE
mail_tracking_mailgun

### ISSUE THREAD

**Issue by steven-bouillon** [OCA/social#553]
I'm sorry if this is not the appropriate way to ask a question about this module but the developers asked to not be contacted directly.

Is it possible to modify this module support postmark? I'm not as knowledgeable on python code as 99% of you that read this so ANY, literally any, insight you can provide would be greatly appreciated.

https://www.postmarkapp.com

Thank you~

**Comment by pedrobaeza** [comment]
I don't get what's your question

**Comment by steven-bouillon** [comment]
sorry pedro.. I noticed my question wasn't clear or concise. Has anyone been able to use this module for Postmark? Would I be able to use Postmark's API keys in this module to make it work with their service or would it be a major re-work?

I appreciate any input.

Thanks Pedro.

**Comment by steven-bouillon** [comment]
I will close this right after I get an answer. I didn't feel right making an "issue" out of this but I also didn't know where else I could ask. Thank you~

**Comment by pedrobaeza** [comment]
No, this module is only for Mailgun and works only with its API (legacy one). I close it for you.
