### ISSUE TITLE
[13.0] mail_activity_board activities not removed when removing record

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/social#556]
See video:
https://drive.google.com/file/d/1TuPwzCKDffDV-Ypd8NW29XLk1yzRqE2C/view

When mail_activity_board is installed and the underlaying record is removed the activity is not removed. When trying to open the activity it's not shown.

@pedrobaeza

**Comment by pedrobaeza** [comment]
Sorry, not involved in that module.

**Comment by CasVissers-360ERP** [comment]
@MiquelRForgeFlow 
@dajuayen 
Look's like a prio issue to me? I tried to solve it but wasn't able to do so.

**Comment by MiquelRForgeFlow** [comment]
I cannot see the video, it says it didn't exist.

**Comment by CasVissers-360ERP** [comment]
@MiquelRForgeFlow 
https://drive.google.com/file/d/1vgNLwhEvGEp0FD_kssyaYLGyVPoimwF-/view

Also tried on v12 runbot. Bug is unique to v13.

**Comment by MiquelRForgeFlow** [comment]
Solved in https://github.com/OCA/social/pull/564.
