### ISSUE TITLE
[13.0] [BUG]"mail_activity_board" module > Getting bug when schedule activity (activity type to perform : upload Document ) "on any object

### ISSUE THREAD

**Issue by NCS-75** [OCA/social#558]
Context : 
OCB 13.0 Odoo Server up to date [(06/25/2020),] with Virgin database , to reproduce issue faced on my test environnement, and also on runbot : http://3426400-13-0-433cb9.runbot2-3.odoo-community.org

Steps to reproduce :
Install "mail_activity_board" module
Go to any object record where you can schedule an activity, (eg: contact form) and try to schedule an new activity  as "upload document" type (only faced on this type ; not other) ; then, we get the following image track  issue on page..

Consequence:
Regardless screen track issue displayed,  the activity scheduled is recorded..., and impossibility to return back to the object form (contact) 

Resiliancy: 
Need to go to Setting/Emails/activities, and delete this activity row concerned.
Then after deleted, can go back to object form..

**As soon as module is uninstalled ; issue disapeared !!**
.

![Capture_2](https://user-images.githubusercontent.com/59052920/85729813-68d31f80-b6f9-11ea-9311-63841e00406d.JPG)
![Capture_3](https://user-images.githubusercontent.com/59052920/85729846-6f619700-b6f9-11ea-8bae-97153f86c133.JPG)

@MiquelRForgeFlow 
@dajuayen 
@lmignon #473

**Comment by NCS-75** [comment]
Hi
@MiquelRForgeFlow 
@JordiBForgeFlow 
@lmignon
@CasVissers
Does someone agree with this bug ?
Thanks

**Comment by ygol** [comment]
on runbot I got rid from that error after uninstalling mail_activity_done (cf. https://github.com/OCA/social/issues/675)
