### ISSUE TITLE
[12.0] Is there an addon for auto-starred incoming messages?

### ISSUE THREAD

**Issue by victoralmau** [OCA/social#572]
In many situations, many incoming emails are received from many models in which Odoo correctly marks inbox as unread, but the moment we enter the registry they are marked as "seen" and disappear, making it "easy" for any message to be left without do.
Perhaps an addon would be useful for the community that marks all the incoming messages from clients to the followers of the registry in question as auto-starred (thus forcing each user to unmark it).

Is there something similar and / or would it be useful?

**Comment by pedrobaeza** [comment]
It can be rules by content, by issuer, by recipients, etc, similar to Gmail filters.
