### ISSUE TITLE
[12.0] mail_tracking: Lot of concurrent updates when calling the open url

### ISSUE THREAD

**Issue by rousseldenis** [OCA/social#589]
```
bad query: b'UPDATE "mail_tracking_email" SET "state"=\'opened\',"write_uid"=1,"write_date"=(now() at time zone \'UTC\') WHERE id IN (4740)'
ERROR: could not serialize access due to concurrent update
```

This is the error raised when calling the url : https://(...)/mail/tracking/open/(...)/blank.gif

**Comment by pedrobaeza** [comment]
We are not experiencing this in our deployments. There can be a chance of this happening if you have the record locked (doing an edition for example), but the probability is low. You should also mention your Odoo version. Is this always happening in your DB?

**Comment by rousseldenis** [comment]
> We are not experiencing this in our deployments. There can be a chance of this happening if you have the record locked (doing an edition for example), but the probability is low. You should also mention your Odoo version. Is this always happening in your DB?

It seems that the update query is launched twice (same id, same log time). I can explore a little bit more. Maybe the blank.gif is inserted twice in mail ?

**Comment by pedrobaeza** [comment]
Not sure about the duplicity... if you can analyze an affected mail we can clear this doubt, but if it's twice, why I'm not experiencing this problem? Can you try in a fresh DB with no other addons?

**Comment by rousseldenis** [comment]
> Not sure about the duplicity... if you can analyze an affected mail we can clear this doubt, but if it's twice, why I'm not experiencing this problem? Can you try in a fresh DB with no other addons?

Of course, I'm on it

**Comment by rousseldenis** [comment]
> Can you try in a fresh DB with no other addons?

Maybe it is specific to a situation, so first debugging with full data

**Comment by pedrobaeza** [comment]
OK, let me know anything.

**Comment by rousseldenis** [comment]
It seems that status is well updated.

But, the query that has succeeded is executed few time before the failing one.

I'm wondering if the state should be checked before executing the tracking.write({'state': state')}): https://github.com/OCA/social/blob/12.0/mail_tracking/models/mail_tracking_event.py#L101

Checking transitions between states would be better I think in order to lower the possible amount of queries. What do you think ?

**Comment by pedrobaeza** [comment]
I remember that it was designed that way for avoiding inter-locks reading and writing, but it was done this way on v8, so things might change.
