### ISSUE TITLE
[13.0] [BUG]"base_search_mail_content" module > Getting bug with "hr" (Employees) module

### ISSUE THREAD

**Issue by NCS-75** [OCA/social#603]
module: base_search_mail_content
version: 13.0

**Context :**
OCB 13.0 Odoo Server up to date [(08/30/2020),]
Virgin database , to reproduce issue faced on my test environnement.
Also !! >> Get same bug on runbot : http://3437172-13-0-56e0a2.runbot2-2.odoo-community.org

**Steps to reproduce**
- Install together  "base_search_mail_content" & "hr" (Employees) native odoo module, and try to access to : hr" (Employees)

**Current behavior**  (model=hr.employee&view_type=kanban, or tree)
When i try to access to menu "Employees"There is this following message : 
> Something went wrong !
Only types ['many2one'] are supported for category (found type text)

**Current resolution**
i uninstall "base_search_mail_content" to retreive access to hr" (Employees)

-----------------------------------------------------------------------------------------------------------------------
![Capture-Access _employees-1](https://user-images.githubusercontent.com/59052920/91721693-74c7db80-eb99-11ea-8871-c5a5b0b21eac.JPG)
![Capture-Access _employees](https://user-images.githubusercontent.com/59052920/91721766-932dd700-eb99-11ea-8c2b-12a280df4217.JPG)

**Comment by BT-aestebanez** [comment]
Same here: http://3440272-13-0-7d4692.runbot2-2.odoo-community.org/web#action=&cids=1&menu_id=284
with Recruitment

**Comment by pedrobaeza** [comment]
Fix in #623 

Please review it

**Comment by BT-aestebanez** [comment]
Tested in the runbot of the PR https://github.com/OCA/social/pull/623 
It works with Recruitment
