### ISSUE TITLE
[13.0] mail_debrand ISSUE

### ISSUE THREAD

**Issue by sergioeix** [OCA/social#607]
Odoo 13 community Ubuntu 18.04
Hello I installed this module and i noticed that on my side its not working anyway and i cant offer more info but when installed every mail still branded by odoo, i tried the language issue mentioned on other odoo 12 thread but no way, i dont know if i am the only one with this issue.
B/R

**Comment by yung-wang** [comment]
I tried today also, it seems to look hardcoded for 'powered by' and try to remove that. But if you use a different language for your mail, nothing got debranded.

See issue #441

**Comment by sergioeix** [comment]
I have installed English and spanish and got the same issue on the 2 languages, but let me check in deep on English because i do a single send to try.
B/R

**Comment by astirpe** [comment]
@sergioeix I'm proposing a fix in https://github.com/OCA/social/pull/613, would you give it a try?

**Comment by yung-wang** [comment]
@astirpe I tested and approved the fix. It is working for Dutch and English. @sergioeix Please test, so this fix will be merge sooner.

**Comment by sergioeix** [comment]
@astirpe @yung-wang I test it and its working on spanish lang
