### ISSUE TITLE
[RFC] Marketing Automation

### ISSUE THREAD

**Issue by mileo** [OCA/social#625]
Hi,

We are planning to create a module of marketing automation.

Searching on the web we found this JS widget: https://github.com/alyssaxuu/flowy

![Demo](https://media.giphy.com/media/dv1C56OywrP7Cn20nr/giphy.gif)
<br>A javascript library to create pretty flowcharts with ease

Any one knows a similar or a better JS lib?

CC: @hendrixcosta

**Comment by angelmoya** [comment]
No this way.... but I did a module to creare Marketing Automation with Activities, with three main functionalities:
- mail.activity can be set as date a time.
- mail.activity can be set a auto=true, if is auto=true on datetime activiti will be done atomatically.
- mail.activity can execute a ir.action.server when is done.

This ir.action.server can plan other mail activity... this way you can execute serveral actions to manage automatic workflow for example in leads.

**Comment by mileo** [comment]
> No this way.... but I did a module to creare Marketing Automation with Activities, with three main functionalities:
> 
> * mail.activity can be set as date a time.
> * mail.activity can be set a auto=true, if is auto=true on datetime activiti will be done atomatically.
> * mail.activity can execute a ir.action.server when is done.
> 
> This ir.action.server can plan other mail activity... this way you can execute serveral actions to manage automatic workflow for example in leads.

Nice... Can we review the code?

**Comment by angelmoya** [comment]
OK, I will do a PR this week

**Comment by mileo** [comment]
> OK, I will do a PR this week

Any news?

**Comment by bealdav** [comment]
Hi @angelmoya Curious to see your code on this topic

**Comment by mileo** [comment]
@hendrixcosta Push some modules related here: https://github.com/hendrixcosta/social

**Comment by angelmoya** [comment]
Hi @bealdav @mileo sorry for delay..

I would like to migrame module to latest versión, and improve to do according OCA standars... but I had no chance

This is the module that is working on version 11.0, on a customer without problems for 2 years.

https://github.com/PESOL/social/tree/11.0-ADD_mail_activity_auto

Only one thing to take care, and its that for this customer activities date was changed to datetime.... but the rest would work right.

The module is simple:
- Mail activity has auto and action server field, if auto = True then this activity will be mark as done on date due. And nest proposed activity will be created.
- If auto = True and you have action server related, this action server will be done.

This action server can send emeail or do whatever...

**Comment by angelmoya** [comment]
Hi, finally I will migrate this module to version 14.0 in next months, and I would like to do in OCA

**Comment by sschuetz2bit** [comment]
Hi @angelmoya 
Whats the status of the migration?

**Comment by angelmoya** [comment]
Hi @sschuetz2bit sorry, but finally we do not do it... 

The main problem is that in previous version we did change activities date to datetime, and we don't want to do it on newest  versions.

Then we can automatize activities, but we don't know at what time it will launch, and also we can have a lot of task to launch each day, at same time... so we think that could be better to integrate with queue job, but we ned to develop it.

**Comment by sschuetz2bit** [comment]
Thanks for the update!

**Comment by lcbolt** [comment]
Hi all! In the meantime, is there any update on a marketing automation module in 16.0? The [flowcharts](https://github.com/alyssaxuu/flowy) that were referred to look very useful.

**Comment by gregory-moka** [comment]
Hello there,

We have a project that is totally linked to `Marketing automation` features. 
It could be nice **to work together on a first version** of this addon.

### Dedicated repository ?
Maybe it would more practical to have a dedicated repository on OCA to work on it. It will have sense cause the marketing automation will provide default behaviours (like SQL search, activities based on time, or last action...) and link with other addons (`website`, `contact`, `sales`, `invoicing`, `purchase`...).
So, if we plan to have it on social repo, it will quickly become a mess.
What is your opinion @pedrobaeza :)

### First ideas to initiate the project
To work on this feature, it will be nice to talk about it to start on a really first version that answer at least to those needs : 
- New "**App menu**" ?
- Kanban view > To organize scenarios (draft, active, done)
- Form view to create and organise scenarios (based on a kind of form view we can have on `hr.leave.accrual.plan` ([see example](https://58262222-16-0-all.runbot105.odoo.com/web#id=1&cids=1&menu_id=263&action=351&model=hr.leave.accrual.plan&view_type=form)) ? > Maybe possible to have forks and parallels routes betweens conditions)
![image](https://github.com/OCA/social/assets/45974412/3a268047-6d5d-4808-b816-934148ab3143)

- Form view for conditions (SQL condition, time condition, action > Base on the `base_automation` jobs :
![image](https://github.com/OCA/social/assets/45974412/77f4ecb0-49b8-429f-bec3-abbb184d044e)

If you have more accurate ideas, please use this thread to contribute.
Thanks

**Comment by pedrobaeza** [comment]
Out of the Spanish Odoo Association (AEOdoo - Asociación Española de Odoo), we have made a bid for developing this tool, and it has been granted to @etobella, whom will develop it on the next months. The specification is already stated in https://www.aeodoo.org/blog/licitaciones-cerradas-3/licitacion-desarrollo-automatizacion-de-marketing-61, but things may vary a bit if he sees that it's more convenient, so ideas are welcome.

About a new repository, it can be indeed an option.

**Comment by gregory-moka** [comment]
> Out of the Spanish Odoo Association (AEOdoo - Asociación Española de Odoo), we have made a bid for developing this tool, and it has been granted to @etobella, whom will develop it on the next months. The specification is already stated in https://www.aeodoo.org/blog/licitaciones-cerradas-3/licitacion-desarrollo-automatizacion-de-marketing-61, but things may vary a bit if he sees that it's more convenient, so ideas are welcome.
> 
> About a new repository, it can be indeed an option.

Thank you for answer and congrats for the project. Let us know if we can help.

**Comment by etobella** [comment]
I will start working on this at the begining af march, I will warn you as soon as I start
