### ISSUE TITLE
[13.0] mail_tracking issue when set all as reviewed

### ISSUE THREAD

**Issue by sergioeix** [OCA/social#629]
13 Community Ubuntu 18
When try to set all as reviewed on #general or other channel doesnt matter wich one this error is shown:
![image](https://user-images.githubusercontent.com/62206774/96641328-da784e80-1324-11eb-984d-9e93f03e0b70.png)
Fully reproducible on runbot
B/R

**Comment by pedrobaeza** [comment]
This is fixed by #624 when ported to 13.0. The button shouldn't appear there.

**Comment by sergioeix** [comment]
This button is still there, its also shown on runbot enviroment actually.
![image](https://user-images.githubusercontent.com/62206774/96783250-c0567300-13ed-11eb-9dfa-8a2c41b15a0d.png)

**Comment by pedrobaeza** [comment]
Are you talking about the runbot of the mentioned pr?
