### ISSUE TITLE
mail_restrict_follower_selection - Restrict follower selection for a certain record type

### ISSUE THREAD

**Issue by AkshayaGovindarajan** [OCA/social#643]
The module mail_restrict_follower_selection restricts the followers globally but not for certain record. E.g if i want to restrict the followers on helpdesk.ticket , its not working. I tried it in the odoo v13.0. If its working for certain record, could someone give me the example of system parameter?

Thank you

**Comment by bodedra** [comment]
cc @pedrobaeza @JoanSForgeFlow @etobella @phucngta
