### ISSUE TITLE
[13.0] mass_mailing_partner: Mailing list contact with an empty "email" field displays an error

### ISSUE THREAD

**Issue by RachidAlassir** [OCA/social#644]
Create a mailing list contact without email (_email field is not required_) an error will be displayed.
The issue is [here](https://github.com/OCA/social/blob/13.0/mass_mailing_partner/models/mailing_contact.py#L105) where `self.email` is `False`.

Screenshot:
![image](https://user-images.githubusercontent.com/48803268/101099565-2c1f2480-35c5-11eb-914a-1de768a95784.png)

**Comment by pedrobaeza** [comment]
I thought email was required, but I see that is not. 8fb1fc0 fixes this.
