### ISSUE TITLE
[13.0][BUG] mail_outbound_static: Whilelist based logic not working

### ISSUE THREAD

**Issue by COSTLAND** [OCA/social#653]
module: mail_outbound_static
version: 13.0

**Steps to reproduce**
- ...using Odoo.sh DEV branch
- Install module: mail_outbound_static, CRM
- Setting - External Email Servers - Enable
- Setup SMTP with testing credential

- Setup each outgoing server with whitelist

> SMTP server 1: (default server as priority is highest)
> server: smtp.mailgun.com
> user name: login-1
> whitelist domain: company-1.com 
> Email From: empty
> 
> SMTP server 2: 
> server: smtp.mailgun.com
> user name: login-2
> whitelist domain: company-2.com
> Email From: empty

- Change current user email address to test@company-2.com
up right corner - user Preferences - email address

Then, go to CRM to reply any of the pipeline (as message type reply). 

**Current behavior**
- The message is sending though the SMTP server 1 (default) regardless the FROM address is test@company-2.com
- wrongly using the default SMTP server sending out the message instead of Whitelist based logic

**Expected behavior**
using the whitelist logic in message type of email

* note: the SMTP server is accepting all mail address within the authorized domain.
- Means it accept user1@company-1.com, or user2@company-1.com using the same credential, as long as the domain is from company-1.com
- User name in SMTP setup didn't reflect the actual email address

**Comment by RFoerster** [comment]
Hi Costland - did you find any solution to this issue?
I was able to find out that the send_mail - method provides the correct mail_server_id, but in the original send_mail method that is called via Super() there is also an smtp_session present which will overwrite the mail_server_id set - thus Odoo will use this existing connection which uses the SMTP-Server with a higher priority (lower sequence). However - not yet sure how to solve this issue properly.
