### ISSUE TITLE
Updating the Sendgrid module to Odoo 13

### ISSUE THREAD

**Issue by themreza** [OCA/social#669]
@ecino

I looked into your repository and it seems like you've been working on the Sendgrid module for Odoo 12 (https://github.com/CompassionCH/social/tree/12.0-sendgrid-all).

Is it possible to update it for installation on Odoo 13?

If you couldn't upgrade it yourself, I appreciate if you hint what needs to be upgraded.

**Comment by ecino** [comment]
Hello, no plan to upgrade on our side, we switched over to mailchimp. I don't know really what would be needed for v13 as we are astill using Odoo 12. The sendgrid modules were working on v12 so I would start by testing this version (it is on the branch you referrenced above) over Odoo 13 and see from there what would be needed.

**Comment by themreza** [comment]
Thanks. I'll take a look and try to upgrade them.
