### ISSUE TITLE
RFC manage your daily job with messages and activities, i.e leads

### ISSUE THREAD

**Issue by bealdav** [OCA/social#686]
Use case example but can be applied on any model:

- you need to check what's happens on leads. 
- lead form describe what the lead are but not what are next actions and what's happened in the past
- you need to check many leads at once, first see those with most events on them to manage your teams vendors
- you have to filter relevant messages or activities based on your own criteria
- some systematic odoo message must be exclude because they no added value for you business management
- a tree view on your object could be a good starting point

Possible implementation:

- define an sql view to group mail.message with mail.activity
- apply domain to exclude noisy and irrelevant odoo messages
- allow to group by user and lead, etc
- quick access on concerned lead
- quick create new message/activity
- ... to complete

cc @clementmbr @MiquelRForgeFlow @pedrobaeza @Yajo @JordiBForgeFlow @LoisRForgeFlow @alexey-pelykh @sebastienbeau

**Comment by pedrobaeza** [comment]
I haven't found such need, and the needed ones are covered with kanban view with the activities icon (the clock) with colors for differentiating late/today/future activities + individual notifications when replies come to the system, but I'm not a deep user of the CRM, having only 3-4 leads per day.

**Comment by JordiBForgeFlow** [comment]
mail_activity_board is useful as a central panel of your activities, pending and completed (using mail_activity_done). 

In your Discuss you have access to all your incoming emails already. 

A combined object? I'm not sure..
