### ISSUE TITLE
mail_activity_team: auto created activity is blocked by team constraints

### ISSUE THREAD

**Issue by chienandalu** [OCA/social#688]
Steps to reproduce (with `hr_holidays`):

- Create an employee linked to a user with another user as the employee responsible.
- Set a mail activity team for that user and another team for the responsible.
- Ask for a leave.
- A `ValidationError` raises: **The assigned user is not member of the team.** (https://github.com/OCA/social/blob/12.0/mail_activity_team/models/mail_activity.py#L70-L74)

What's happening is that when we ask for a leave a `mail.activity` is automatically created for the responsible user, but the `mail_activity_team` module defaults instead to the team of the user that is creating the activity.

As I don't understand very well the reason of the constraint, some guidelined would be welcome to apply a fix that avoids this issue.

ping @MiquelRForgeFlow @JordiBForgeFlow @etobella @bealdav @AdriaGForgeFlow

**Comment by chienandalu** [comment]
Anybody? :sweat_smile:

**Comment by MiquelRForgeFlow** [comment]
> - Create an employee linked to a user with another user as the employee responsible.
> - Set a mail activity team for that user and another team for the responsible.
> - Ask for a leave.

Do you do that manually?

The onchanges are there to make sure the activity has 1) a team or 2) has a responsible or 3) has both, which the responsible is in the team. Thus, if any of the onchanges have been executed, then the constraint shouldn't be blocking the activity.

It seems to me the root of the error is that when you ask for a leave, the automatically leave created doesn't trigger the onchanges. We should update the code, I don't know where, to assure that this kind of automatically created activities triggers the onchanges to meet the required constraint requirements.

**Comment by chienandalu** [comment]
Thanks @MiquelRForgeFlow I'll check that :slightly_smiling_face: :+1:

**Comment by chienandalu** [comment]
Here's the PR: https://github.com/OCA/social/pull/696
