### ISSUE TITLE
[12.0] mail_tracking: SpamAssassin flag 'RAND_MKTG_HEADER'

### ISSUE THREAD

**Issue by JorgeQuinteros** [OCA/social#701]
Hello,
Recently some invoice emails that I have been sending through Odoo were not reaching the recipients.They were always to the same customers, and if you sent with the same email account but from Thunderbird for example, it would arrive perfectly.

I have tested with mail-tester to check mail reputation and due to a recent update of SpamAssasin, the headers for Odoo mail tracking detects them as SPAM and drops almost 3 points. This increases the probability of getting into the inboxes of some customers.
![imagen](https://user-images.githubusercontent.com/43784849/115361022-785bb180-a1c0-11eb-847e-b665d88a71ed.png)

![imagen](https://user-images.githubusercontent.com/43784849/115362196-95dd4b00-a1c1-11eb-940a-662b9c1bee13.png)

It appears that if SpamAssasin finds several headers that start with "X-..." and have keywords like "Tracking" it lowers the email's score and may cause problems for certain recipients.
https://bz.apache.org/SpamAssassin/show_bug.cgi?id=7888

If I uninstall the mail_tracking module my score is 10/10.

Has anyone else experienced this?
or any ideas on how to fix this, mail_tracking is a very powerful tool and I would hate to lose it.
Thanks,

**Comment by pedrobaeza** [comment]
Fixed for v13 in #741

**Comment by eLBati** [comment]
Porting to 12.0 with https://github.com/OCA/social/pull/926

**Comment by eLBati** [comment]
Porting to 10.0 with https://github.com/OCA/social/pull/927
