### ISSUE TITLE
When I selected users to send mail invitation portal, the invitation email is not sent?

### ISSUE THREAD

**Issue by Chugarbert** [OCA/social#72]
module: portal_welcome_email_template
version: 8.0

**Steps to reproduce**
Go to sale/customer, select a enterprise and click in button more and clic portal access management. 
Select a employee to send invitation and clic en appli
- ...

**Current behavior**
The invitation email isn't sent,
**Expected behavior**
The user obtain the portal invitation by email

**Comment by pedrobaeza** [comment]
The module is working as expected in my side, so the e-mail not sent should be by another reason (e-mail server configuration).
