### ISSUE TITLE
[12.0] [13.0] [BUG] Wrong form view when opening "mail.activity" registry from calendar view.

### ISSUE THREAD

**Issue by jcBalmes92** [OCA/social#732]
**Impacted versions:**
12.0, 13.0

**Steps to reproduce:**
Go to Dashboards / Activities / Calendar View / Click on one activity to open Form View.

![image](https://user-images.githubusercontent.com/75234645/123317766-64079e00-d4fc-11eb-960b-3e8d18727e77.png)

**Expected result:**
Form view named "mail.activity.boards.view.form" should be open.

**Actual result:**
Form view named "mail.activity.view.form.popup" opens.

**Comment by jcBalmes92** [comment]
This solves the bug:

```
<?xml version="1.0" encoding="utf-8"?>
<odoo>

    <record id="mail_activity_view_calendar" model="ir.ui.view">
        <field name="name">b92.mail.activity.view.calendar.inherit.fix.mail_activity_board</field>
        <field name="model">mail.activity</field>
        <field name="inherit_id" ref="mail.mail_activity_view_calendar"/>
        <field name="arch" type="xml">
            <xpath expr="/calendar" position="attributes">
                <attribute name="readonly_form_view_id">%(mail_activity_board.mail_activity_view_form_board)s</attribute>
                <attribute name="event_open_popup">true</attribute>
            </xpath>
        </field>
    </record>

</odoo>
```

According to [this documentation](https://www.odoo.com/documentation/12.0/developer/reference/views.html#calendar), this attributes needs to be present in a calendar view if you want to force a specific form view:

- readonly_form_view_id
- event_open_popup

**Comment by jcBalmes92** [comment]
@victoralmau @pedrobaeza

**Comment by pedrobaeza** [comment]
This module is not ours.
