### ISSUE TITLE
[14.0][mail_tracking] Need to support OWL framework

### ISSUE THREAD

**Issue by ska-ibees** [OCA/social#740]
Due to JS framework migration to OWL framework in Odoo 14. JS modules in mail_tracking are failed to load dependencies and inheritence/extention also need to support OWL framework.

**Comment by pedrobaeza** [comment]
Can you check @angelJuaGar @moylop260 ?

**Comment by alan196** [comment]
This issue is fixed with this PR #792

I have tested it in my production database and it works 👍
