### ISSUE TITLE
[12.0] mail_tracking - js error when clicking on a contact name

### ISSUE THREAD

**Issue by MAG-Florian-Chevalier** [OCA/social#743]
Hi,

I'm getting the js error shown by this screenshot when I click on the purples names (in the "To" field) in a private message (and only here)
![Screenshot_20210712_123021](https://user-images.githubusercontent.com/73696844/125273273-0a311180-e30d-11eb-8f5e-7f5064e92eb4.png)
It's working properly when trying to access the same "link" in ant form view.

Regards

**Comment by pedrobaeza** [comment]
Please indicate complete steps to reproduce the problem in an OCA runbot instance.

**Comment by MAG-Florian-Chevalier** [comment]
Mail_tracking's runbot on v12 wasn't accessible so I forced a rebuild but it apparently failed (here's the link to it : https://runbot.odoo-community.org/runbot/build/3492550). 
Is there another way to test the module on runbot or to rebuild ?

**Comment by pedrobaeza** [comment]
You have to rebuild, but you can also express full detailed instructions to get to the error.

**Comment by MAG-Florian-Chevalier** [comment]
Here are the steps to reproduce the error:
- Go to a partner's page and send a message with another user as follower
- Log in as the other user (which was following), he should have a message notification for this.
- When you click on the message notification, the small window for messages should appears at the bottom of the screen
- In this window, just above the body part of the message, there is a "To" line added by this module, where the partner's names are written in purple color. When I click on this, I got the error

I'll try to reproduce on runbot when it will be accessible.

**Comment by MAG-Florian-Chevalier** [comment]
12.0 runbot failed three times and here are the logs I can find :
> Unable to find image 'oca-social:47fe5f4_env_1_job_2' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout.
See 'docker run --help'.

**Comment by pedrobaeza** [comment]
OK, a video may help as well to identify the issue.
