### ISSUE TITLE
[14.0] mail_tracking - Contact > 'MailTracking emails' is searching for email using contains instead of equal

### ISSUE THREAD

**Issue by samannisar** [OCA/social#752]
Pre-Condition: Your database should have enough data so you can see test result and emails sent to those contacts. 

Steps to Reproduce:
1. Go to a Contact
2. Go to 'MailTracking emails' menu

Issue: The 'MailTracking emails' searches for the main email from the entire database for all emails related to the given contact. 
It uses contains for search instead of equal. 

For example: Let's say contact's main email = saman@gmail.com
Database has other emails as saman.nisar@gmail.com , saman.shahid@gmail.com, saman.sameer@gmail.com, samankhan@yahoo.com, chsamanahmed@hotmail.com   (Random emails used for examples)

In this case the contact's mail tracking email shows  Emails from all above email address as related to the given contact. 
But in reality those emails belong to other contact and not this contact. 

System uses "saman" , "gmail" and search for all emails with "saman" and "gmail" in the email.   

Please fix and use the equal value for searching so given contact only displays emails related to that contact ONLY.

**Comment by pedrobaeza** [comment]
Do you mean searching on the search bar?

**Comment by samannisar** [comment]
![image](https://user-images.githubusercontent.com/59840077/127196107-1243d050-49b0-4c47-9106-da3714440f7b.png)


That's the auto search that happens when you go to contact then mail tracking.

**Comment by pedrobaeza** [comment]
OK, understood. @angelJuaGar @moylop260 can you check (although I suspect this is not something of the latest migration)?
