### ISSUE TITLE
[12]mail_tracking: error when sending mass mail via mail.compose.wizard

### ISSUE THREAD

**Issue by diggy128** [OCA/social#753]
How to reproduce: 
- Go to crm in list view
- Select an opportunity/lead
- Action menu -> mass mail opportunity
- Add some text in mail.compose.wizard pop up and click send

An error is logged regarding insufficient read access rights but no error message in the UI.
The message state in mail.mail is 'exception' and no tracking info is created BUT the message is sent to the recipient.

The error comes up only in 'mass_mail' composition_mode in mail.compose.wizard

PS. I'm not currently on my workstation but I can provide more info as needed.

**Comment by pedrobaeza** [comment]
I don't think the culprit is `mail_tracking` as I have used it in my own system without that problem.

**Comment by diggy128** [comment]
Do you use the mass_mail mode of mail.compose.wizard? 
If that's the case then I'll have to dig deeper because stepping through the code didn't pass through any other modules.

The other thing I can imagine is something going terribly wrong with my record rules...

I'll check again tomorrow and update.

**Comment by pedrobaeza** [comment]
I have just tried it again (but in v13), and no error is returned.

**Comment by diggy128** [comment]
Yes. You were right and so was I.
It was a corner case with custom record rules on mail.tracking when no partner was set.

Thank you @pedrobaeza for taking the time to look into it.

Closing as invalid.
