### ISSUE TITLE
[14.0] [mail_tracking] Can't see tracking icons on contact thread

### ISSUE THREAD

**Issue by delkano** [OCA/social#755]
I'm probably missing something.

I've installed mail_tracking (using the wide load addons list, since I have a multidb install) on my Odoo 14.0 Community server.
I've checked and the sent emails contain the pixel image, the database is correctly updated when the mails are opened, etc.

The only issue is I can't see the mail state on the UI. When I look on a contact page, on the message thread, instead of getting something like the screenshot on the readme, I just get this :
![image](https://user-images.githubusercontent.com/6650309/128882858-130df219-7d1e-406a-9bc4-750b64383360.png)

I've checked the HTML and the classes I have (`o_MessageXXX`) are not like the ones on the src/static/xml/mail_tracking.xml file (`p.o_mail_info`) so it's quite logical that they are not updated, but I can't seem find what should have actually changed not be able to modify the xml myself so I get the right result.

**Comment by pedrobaeza** [comment]
Do you have any special backend theme?

**Comment by delkano** [comment]
Normally yes, but I've also tried on a plain new installation without any installed themes

**Comment by pedrobaeza** [comment]
Are you able to reproduce the problem in OCA runbot?

**Comment by delkano** [comment]
I didn't try an OCA runbot setup, and I don't have an empty server to try it. It might take a while for me to set up a virtual machine or something.

**Comment by pedrobaeza** [comment]
You don't have to populate anything, but use the OCA runbot through the badge "Runbot | Try me" in the README file.

**Comment by delkano** [comment]
Please excuse my ignorance, but which README?

**Comment by pedrobaeza** [comment]
The module README: https://github.com/OCA/social/blob/14.0/mail_tracking/README.rst

**Comment by delkano** [comment]
Ah yes, I looked into that but couldn't find a way to send mails from there, and there are no mail threads on the examples (only several errors).

**Comment by pedrobaeza** [comment]
The important thing is that if you send something (no matter if it doesn't really go out), the tracking line with the recipients is added.

**Comment by delkano** [comment]
This is from the runbot. It doesn't seem much different from my UI, no new line after the header:
![image](https://user-images.githubusercontent.com/6650309/128892968-c53b5deb-2b1d-4d49-8fa1-77217111fdc5.png)

**Comment by pedrobaeza** [comment]
@angelJuaGar and @SimoneVagile you did the migration. Can you tell about this?

**Comment by SimoneVagile** [comment]
@angelJuaGar I think the problem is [here](https://github.com/OCA/social/blob/14.0/mail_tracking/static/src/xml/mail_tracking.xml#L58)

`mail.widget.Thread` templates have been removed in [this](https://github.com/odoo/odoo/commit/3fea5b2136627c1d7e83b2a5e111952fe3eb10a1#diff-8bd58931457097b8c55aa68d5ee188aacaf5f416f277478041369e4b24682c49).

@pedrobaeza any ideas of this?

**Comment by visiniaga** [comment]
any update on this?
having same issue, no icon update while the email tracking is opened, tested in odoo 14 enterprise, already enable wide module in odoo.conf:
server_wide_modules = web,mail_tracking


![mail tracking problem](https://user-images.githubusercontent.com/43309334/131111680-cb078c2e-71d3-40b9-b6c8-4a4df9dd25c4.png)
![mail tracking problem screenshot 2](https://user-images.githubusercontent.com/43309334/131111699-7918ee2e-9b9e-4e4e-a506-092a6ba747e2.png)

**Comment by antuan159** [comment]
I'm also interested in when there will be a fix on this issue
![Screenshot from 2021-08-27 15-56-35](https://user-images.githubusercontent.com/42843350/131130805-0f23e3d5-53de-4c9a-8fb3-2a7cf0c6d159.png)

**Comment by TesaLazarenko** [comment]
I am very much looking forward to correcting the problem. Thanks.

**Comment by VitaliiHlapshunSmartteksas** [comment]
Hi there!
Looking forward to get updates and fixes regarding the issue as well.
Thanks in advance.

**Comment by pedrobaeza** [comment]
@moylop260 it seems you migrated half the module. Can you please restore this part?

**Comment by SimoneVagile** [comment]
@pedrobaeza @antuan159 check for [https://github.com/OCA/social/issues/755#issuecomment-896715631](https://github.com/OCA/social/issues/755#issuecomment-896715631), I think this is the key.

**Comment by kmagusiak** [comment]
I think this is a duplicate of https://github.com/OCA/social/issues/740. Odoo indeed migrated some of the GUI to OWL framework.

**Comment by ao-landoo** [comment]
I just tested this module and it's not working correctly.

**Comment by moylop260** [comment]
Sorry, I don't get you

What is wrong here?

Could you open an issue with steps to reproduce it, please?

**Comment by alan196** [comment]
This issue is fixed with this PR https://github.com/OCA/social/pull/792

I have tested it in my production database and it works 👍

**Comment by visiniaga** [comment]
Great, it works tested in 14.0+e-20211018

thanks

**Comment by pedrobaeza** [comment]
Fixed already.
