### ISSUE TITLE
mail_tracking_mailgun webhook error on creation.

### ISSUE THREAD

**Issue by promotobillet** [OCA/social#761]
While testing/creating webhook in Mailgun I get the following error:
I am unsure if its my setup or a bug.  All configurations in Odoo look set correctly (and as they did in Odoo v10 which we migrated from, and where we used the module in the past).

It may also be because Mailgun now has a new webhook setup. I used their **legacy webhooks** that works perfect.

Response: {"jsonrpc": "2.0", "id": null, "error": {"code": 200, "message": "Odoo Server Error", "data": {"name": "werkzeug.exceptions.BadRequest", "debug": "Traceback (most recent call last):\n  File \"/odoo/odoo-server/odoo/addons/base/models/ir_http.py\", line 237, in _dispatch\n    result = request.dispatch()\n  File \"/odoo/odoo-server/odoo/http.py\", line 683, in dispatch\n    result = self._call_function(**self.params)\n  File \"/odoo/odoo-server/odoo/http.py\", line 326, in _call_function\n    raise werkzeug.exceptions.BadRequest(msg % params)\nException\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/odoo/odoo-server/odoo/http.py\", line 639, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/odoo/odoo-server/odoo/http.py\", line 315, in _handle_exception\n    raise exception.with_traceback(None) from new_cause\nwerkzeug.exceptions.BadRequest: 400 Bad Request: <function MailTrackingController.mail_tracking_event at 0x7fd75b753a60>, /mail/tracking/all/Production: Function declared as capable of handling request of type 'http' but called with a request of type 'json'\n", "message": "400 Bad Request: <function MailTrackingController.mail_tracking_event at 0x7fd75b753a60>, /mail/tracking/all/Production: Function declared as capable of handling request of type 'http' but called with a request of type 'json'", "arguments": [], "context": {}}}}

**Comment by pedrobaeza** [comment]
Are you using old style webhooks? They are needed for this to work.

**Comment by promotobillet** [comment]
Yes I am using legacy webhooks now and they work. Thanks

Maybe the readme can reference that, since Mailgun and updated to a new version.

**Comment by pedrobaeza** [comment]
It was incorrectly added in #430. Can you please propose a PR re-adding this in the proper place (readme/ROADMAP.rst) and put the proper steps in readme/CONFIGURE.rst?
