### ISSUE TITLE
[14.0] mail_tracking: button 'Tracking emails' in partner is showing a different count that shown when you click on it

### ISSUE THREAD

**Issue by fernandahf** [OCA/social#803]
The mail_tracking in v13 is searching the emails as follows:

https://github.com/OCA/social/blob/78daea28e5763cb132c77fcc986408680dd4e84f/mail_tracking/models/mail_tracking_email.py#L203-L214

It's using a regex to catch cases when the recipient is `<(emailexample@.example.com)>` and if regex is not matched, it's using the email like comes in the record, but in v14.0 is using the function `email_split` and it's only considering when exactly matching and excluding the emails as `<(emailexample@.example.com)>`

https://github.com/OCA/social/blob/147eda96a56c199602c619b5bac3a9911605e918/mail_tracking/models/mail_tracking_email.py#L204-L210

## Module
mail_tracking

## Describe the bug

The mail_tracking in v13 is searching the emails as follows:

https://github.com/OCA/social/blob/78daea28e5763cb132c77fcc986408680dd4e84f/mail_tracking/models/mail_tracking_email.py#L203-L214

It's using a regex to catch cases when the recipient is `<(emailexample@.example.com)>` and if regex is not matched, it's using the email like comes in the record, but in v14.0 is using the function `email_split` and it's only considering the when exactly matching and excluding the emails as `<(emailexample@.example.com)>`

https://github.com/OCA/social/blob/147eda96a56c199602c619b5bac3a9911605e918/mail_tracking/models/mail_tracking_email.py#L204-L210

## To Reproduce
14.0

1. Go to any partner with mails sent.
2. See the emails shown in button `Tracking emails` 
3. Click on button `Tracking emails` 
4. See that is likely it doesn't show the emails correctly

**Expected behavior**
The expected behavior is user sees the same count of emails in `Tracking emails` that when you click on it.

**Comment by pedrobaeza** [comment]
Have you updated after #779 ?

**Comment by fernandahf** [comment]
@pedrobaeza 

I just tested with the fix of 779 but it is showing a different count `Tracking Emails ` than emails shown when clicking on it, too.

Smart Button:

![Screen Shot 2021-11-18 at 12 53 04](https://user-images.githubusercontent.com/54731581/142478572-2052038c-e4ac-4c82-b5da-86e03293b106.png)

Tree view mail tracking (It's showing 24)

![Screen Shot 2021-11-18 at 12 53 15](https://user-images.githubusercontent.com/54731581/142478584-fe65af13-ec75-473f-b589-029274a4aa64.png)

Maybe it needs a change in the compute method, too:

https://github.com/Vauxoo/social/blob/c44a158bf8a969efaa0f3194f5f12a1dc8dce67e/mail_tracking/models/res_partner.py#L18-L30

**Comment by pedrobaeza** [comment]
Ok, then any PR for fixing this is welcome. Please take into account the performance.
