### ISSUE TITLE
Backport support for Google Mail OAuth authentication for Odoo <= 11.0

### ISSUE THREAD

**Issue by gurneyalex** [OCA/social#860]
Google announced that they will be requiring oauth for mail access starting on may 30, 2022.

Odoo has made changes starting on version 12.0 (https://github.com/odoo/odoo/commit/336c9aab3619abb5bfbeb07f87ae014facdefb0b) to add this support.

We need to backport this to addons for version 11.0 and before.

**Comment by dreispt** [comment]
I feel that the https://github.com/OCA/server-auth repo is more adequate for this.

**Comment by pedrobaeza** [comment]
I don't think so, as that's for Odoo authentication methods, not for mailing.

Remember to put on the README the Odoo backport disclaimer and put the initial commit with the module as is extracted from Odoo attributed to for example `info@odoo.com`.

**Comment by dreispt** [comment]
@pedrobaeza Right, that makes sense.

**Comment by yajo** [comment]
I think OCB is the place. After all, it only exists with the purpose of backporting stuff from Odoo 🤷🏼‍♂️. The fix linked alters the fetchmail module, which is ubiquitous. I don't see any benefit on increasing the complexity of the backport (having to separate some parts of the commit in OCB and some other parts in a separate module in another repo).

**Comment by gurneyalex** [comment]
I tend to agree with @Yajo here: it seems to me that a fix in OCB would be easier, and these modules don't need to evolve over time and be migrated forward.

**Comment by pedrobaeza** [comment]
OK, as you prefer. OCB is not very prepared in CI terms, but seeing the Odoo commit, there's a minimal change to be done on core `fetchmail` module and  `base`, so that one is needed to be on OCB or monkey-patched in the module, so it can be easier to be done on OCB.

**Comment by simahawk** [comment]
:+1: for OCB

**Comment by gurneyalex** [comment]
Do we need an update in mail_environment or maybe a new module in https://github.com/OCA/server-env ?

**Comment by dreispt** [comment]
AFAIU  OCB is for bugfixes, not feature backports.
The rule was to early merge upstream proposed PRs (even if rejected by Odoo)

In the cases where an Odoo module was back or forward ported, that was done as a module in the appropriate repo.
My feeling is that this should be an OCA/social module, extracted from Odoo and backported.

**Comment by yankinmax** [comment]
I opened PR to resolve this issue. Reviews and help is appreciated. Thanks
https://github.com/OCA/social/pull/903

**Comment by PatosMarco** [comment]
Has anyone worked on compatibility with outlook? They stopped at version 12 of Odoo. There seems to be nothing for 11 and 10
