### ISSUE TITLE
[14] mail_drop_target not working

### ISSUE THREAD

**Issue by sergioeix** [OCA/social#875]
## Module
mail_drop_target

## Describe the bug
Tested on runboat. Try to add a mail to any record you cant, this was an issue on 13 and solved with a web_drop_target update #2057 https://github.com/OCA/web/pull/2065 @pedrobaeza 

## To Reproduce
Try to add a mail to any record
**Affected versions**:
14
1. Try to add a mail to any record
2.
3.

**Expected behavior**
as it works on 13 a new box to drop the mail is the chatter zone may be shown

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by COSTLAND** [comment]
Just tested on Odoo V14 EE, we are having the same issue as described. 
- After drop the `eml` or `msg` file into chatter, those file will only stay as attachments instead of chatter message.
