### ISSUE TITLE
[8.0] mail_notification_email_template: E-mails created with template are created with admin rights

### ISSUE THREAD

**Issue by ecino** [OCA/social#94]
When using the module mail_notification_email_template, when sending a message from a chatter box, the generated e-mail is from user Administrator, and it creates user access rights problems when displaying the message.

When the module is not installed (or disable template), the generated e-mail is from the user sending the message. I think that this line is the problem :

https://github.com/OCA/social/blob/8.0/mail_notification_email_template/models/mail_notification.py#L47

But I don't see how it results of an administrator record creation.

**Comment by hbrunn** [comment]
the difference should rather be that the email generated has a different object it is attached to. Can you check this?

**Comment by ecino** [comment]
This is the e-mail generated when clicking "send message" from the chatter box below a res.partner object :
![mail1](https://cloud.githubusercontent.com/assets/8435180/19228588/136f1890-8ec7-11e6-82cd-deaa3a202301.PNG)

This is the same e-mail generated when the module mail_notification_email_template is installed:
![mail2](https://cloud.githubusercontent.com/assets/8435180/19228669/ab37f87c-8ec7-11e6-9887-c0b890f12b0a.PNG)

When I try to access it with the user that sent the message I get an access error.

I looked at the messages object and as you suggested there is a slight difference. Without module installed, it creates a comment type message attached to the res partner with "notified partners" holding followers of the document.

With the mail_notification_email_template module installed, it creates the same message, but it creates as well another message of type email attached to the mail.notification model. This record is created by administrator and may be the one that creates my access rights problems.

First: I don't know why it needs two mail.message records ?
Second: The second created record, if necessary, should as well be created by user instead of administrator, right?

**Comment by hbrunn** [comment]
First: One email to be sent out, the message to be shown under the object in question
Second: It should. I'm not aware of any sudoing involved here, so I'd suggest to debug through to see what's going on there.

**Comment by hbrunn** [comment]
you can probably circumvent your problem by setting auto delete on the email template

**Comment by ecino** [comment]
First: but why without the module, it creates only one mail.message record ? It still generate an e-mail, plus the message is in the mail thread in the object. 

Auto delete was set on the template, so this does not change the behaviour. Maybe I have another module that does this sudo? I will try to debug and see if I can find the issue. Could you confirm if you have the same behaviour?

**Comment by ecino** [comment]
Even with debugging I cannot explain this behaviour, so any help would be appreciated. Here are a few other observations I made:
- email generated with the module have not the "is notification" checkbox
- email generated with the module have not the "reply to" field set
- email generated with the module is from "Administrator" instead of User, like if the user is not detected from the email_from field
- mail.notification record is from "Administrator" instead of User
- creates two mail.message records (one of type "notification" and one of type "email")
- notified partners are set on the "notification type mail.message" record but not on the "email type mail.message record"
- mail.mail record is linked to the "notification mail.message" record

**Comment by pedrobaeza** [comment]
Closing as fixed
