### ISSUE TITLE
[15.0] mail_tracking: When installed portal access links do not work anymore and require login

### ISSUE THREAD

**Issue by llabusch93** [OCA/social#947]
## Module
mail_tracking

## Describe the bug
When mail_tracking is installed, customers without an account are redirected to the login page, when they click for instance the button on a sale order email to sign it.

## To Reproduce
**Affected versions**: 15.0

1. Install mail_tracking
2. Send an email to the customer on sale order with the request to confirm it in the portal (with the "send via email" button on the SO form view)
3. When the link of the button in the sent email is clicked (obviously try it in an incognito browser window), one is redirected to the login page instead to the SO in the portal.

**Expected behavior**
The customer does see his / her SO in the portal order after clicking the button

**Comment by pedrobaeza** [comment]
@chienandalu can you take a look to this? I think I have experimented this also on 13 and 14

**Comment by chienandalu** [comment]
I could reproduce it on runbot. Assign me while I do a deeper research

**Comment by chienandalu** [comment]
This was fixed
