### ISSUE TITLE
[13.0] [14.0] mail_activity_done .- Wrong kanban color of opportunities state if previous activity archived

### ISSUE THREAD

**Issue by antoniocanovas** [OCA/social#957]
Archived activities are used in KANBAN CRM environment resume color status by stage_id.
It's because we ha installed mail_activity_done and completed some activities.

Color status of resume bar is computed including done activities.

## To Reproduce
1. Create an oportunity and activity with previous date (kanban view is red).
2. Complete activity as done, and create the next one as future.
3. Kanban view is red (see attachment).

**Affected versions**:
13 & 14 (at least).

It's related with CRM so I don't know if it must be solved in this module.
I hope it can help.

<img width="630" alt="Captura_de_Pantalla_2022-09-02_a_las_12_18_05" src="https://user-images.githubusercontent.com/8323017/188120103-39040fa4-963d-4f25-b03f-618ac6c03f47.png">

**Comment by lguerrero87** [comment]
Hi Antonio, we have the same issue in 15.0
