### ISSUE TITLE
mail reply didn't attach to the right asset -> possible to move 

### ISSUE THREAD

**Issue by ghost** [OCA/social#969]
Some times depending to the mail client (eg. nextcloud webclient) of the replier there didn't use the reply-to informations in a prober way. So that the message get "lost" .. in our case the reply eg to a sales order appears at a new lead in crm (we fetch all unroutable mails to a lead).

What is the odoo way to repair relation in this case? is it possible to change the relation of a message to a other node with already existing odoo functions?

Or is already a module for moving messages available and i didn't found it?

Or would it a good idea to create a module for moving messages? maybe we could sponsor the development.

**Comment by pedrobaeza** [comment]
This module was done for that purpose: https://github.com/OCA/social/tree/8.0/mail_forward, but it's a bit dangerous in its usage.

**Comment by ghost** [comment]
Thank ou Pedra for fast response.

unfortunately it's not for higher version as 10.0 available. Is it generell a dangerous idea to manipulate this relations? or is this module especially dangerous? Is this problem unique to us or a problem that occurs very often? Then, maybe it gives a better idea to handle this. I ask because we want support and sponsor a good/the best solution for all odoo users.

thx.
